## Collections Data - Phase 1 :Data profiling

In [23]:
import pandas as pd
import numpy as np
import os
from pathlib import Path

In [24]:
DATA_PATH = Path("../data/raw")

In [29]:
files = list(DATA_PATH.glob("*.csv"))

for file in files:
    print(file.name)

accounts.csv
data_dictionary.csv
call_dispositions.csv
field_visits.csv
daily_targeting.csv
call_attempts.csv
promises_to_pay.csv
calls.csv
complaints.csv
whatsapp_events.csv
account_status_history.csv
campaigns.csv
borrowers.csv
payments.csv
vendor_telephony.csv
sms_events.csv
agent_sessions.csv
agents.csv


In [31]:
datasets = {}

for file in files:
    datasets[file.stem] = pd.read_csv(file)

print("Number of datasets:", len(datasets))

for name , df in datasets.items():
    print(name , df.shape)

Number of datasets: 18
accounts (30000, 11)
data_dictionary (143, 3)
call_dispositions (35000, 8)
field_visits (25000, 10)
daily_targeting (45000, 7)
call_attempts (120000, 9)
promises_to_pay (18000, 9)
calls (91350, 11)
complaints (8000, 9)
whatsapp_events (60600, 8)
account_status_history (60000, 8)
campaigns (120, 7)
borrowers (30600, 8)
payments (25500, 9)
vendor_telephony (15, 6)
sms_events (45000, 8)
agent_sessions (15000, 7)
agents (30000, 8)


In [36]:
for name , df in datasets.items():
    print("---------------------------------------------")
    print(name)
    print("----------------------------------------")
    print("Rows" , len(df))
    print("Colums" , len(df.columns))
    print(df.columns.tolist())

---------------------------------------------
accounts
----------------------------------------
Rows 30000
Colums 11
['account_id', 'borrower_id', 'loan_type', 'principal_amount', 'outstanding_amount', 'dpd', 'risk_segment', 'status', 'opened_at', 'timezone', 'schema_version']
---------------------------------------------
data_dictionary
----------------------------------------
Rows 143
Colums 3
['dataset', 'column', 'dtype']
---------------------------------------------
call_dispositions
----------------------------------------
Rows 35000
Colums 8
['disposition_id', 'account_id', 'borrower_id', 'event_at', 'call_id', 'agent_id', 'disposition_code', 'disposition_version']
---------------------------------------------
field_visits
----------------------------------------
Rows 25000
Colums 10
['visit_id', 'account_id', 'borrower_id', 'event_at', 'agent_id', 'visit_type', 'outcome', 'latitude', 'longitude', 'scheduled_at']
---------------------------------------------
daily_targeting
----

In [39]:
for name , df in datasets.items():
    print("\n" ,name)
    display(df.head(5))


 accounts


,account_id,borrower_id,loan_type,principal_amount,outstanding_amount,dpd,risk_segment,status,opened_at,timezone,schema_version
0,ACC0000001,BRW0010742,CONSUMER,603443.40,678074.03,15,MEDIUM,CLOSED,2025-11-11 04:37:00,Asia/Dubai,v1
1,ACC0000002,BRW0009382,BNPL,277190.14,464893.44,5,LOW,ACTIVE,2025-11-13 15:59:44,UTC,v3
2,ACC0000003,BRW0003966,CREDIT_CARD,628658.43,22565.37,60,NPA,WRITEOFF,2025-09-12 04:59:20,Asia/Dubai,v2
3,ACC0000004,BRW0001993,PERSONAL,76435.07,508427.73,30,LOW,CLOSED,2025-05-25 19:29:38,UTC,v2
4,ACC0000005,BRW0009976,CONSUMER,646797.08,563858.01,180,LOW,WRITEOFF,2025-09-07 14:59:13,Asia/Dubai,v2



 data_dictionary


,dataset,column,dtype
0,borrowers,borrower_id,object
1,borrowers,name,object
2,borrowers,phone,object
3,borrowers,email,object
4,borrowers,city,object



 call_dispositions


,disposition_id,account_id,borrower_id,event_at,call_id,agent_id,disposition_code,disposition_version
0,DISPOSITION0000001,ACC0029208,BRW0006282,2026-03-07 17:30:48,CALL0032272,AGT0000759,CALLBACK,v2
1,DISPOSITION0000002,ACC0009584,BRW0000540,2026-04-04 11:59:50,CALL0053880,AGT0000085,CALLBACK,legacy
2,DISPOSITION0000003,ACC0003386,BRW0010257,2026-03-11 01:25:13,CALL0048622,AGT0000319,PROMISE_TO_PAY,v1
3,DISPOSITION0000004,ACC0027899,BRW0006534,2026-03-17 14:49:43,CALL0072651,AGT0000189,NO_CONTACT,legacy
4,DISPOSITION0000005,ACC0024345,BRW0001918,2026-03-07 06:07:26,CALL0036866,AGT0000647,PTP,legacy



 field_visits


,visit_id,account_id,borrower_id,event_at,agent_id,visit_type,outcome,latitude,longitude,scheduled_at
0,VISIT0000001,ACC0026237,BRW0009469,2026-01-25 01:15:48,AGT0000403,AFTER_HOURS,PAID,31.861706,76.098184,2026-01-24 05:49:28
1,VISIT0000002,ACC0026942,BRW0010461,2026-06-23 22:18:25,AGT0000278,NOTICE,PAID,23.641189,74.571935,2026-06-23 14:17:54
2,VISIT0000003,ACC0022809,BRW0006318,2026-05-16 08:06:34,AGT0000723,NOTICE,CONTACTED,22.324370,84.790537,2026-05-16 02:58:39
3,VISIT0000004,ACC0029193,BRW0005195,2026-06-14 00:12:17,AGT0000946,FOLLOWUP,CONTACTED,27.230510,75.957354,2026-06-13 13:32:15
4,VISIT0000005,ACC0015605,BRW0009229,2026-08-01 21:31:09,AGT0000917,NOTICE,REFUSED,23.563588,85.547376,2026-08-01 00:47:29



 daily_targeting


,target_id,account_id,campaign_id,target_date,priority,recommended_channel,status
0,TGT0000001,ACC0028555,CMP0000103,2026-04-22,4,FIELD,QUEUED
1,TGT0000002,ACC0007194,CMP0000100,2026-08-06,10,SMS,EXPIRED
2,TGT0000003,ACC0029550,CMP0000074,2026-05-20,5,SMS,CONTACTED
3,TGT0000004,ACC0012329,CMP0000046,2026-07-30,10,WHATSAPP,QUEUED
4,TGT0000005,ACC0018387,CMP0000118,2026-07-10,7,WHATSAPP,EXPIRED



 call_attempts


,attempt_id,account_id,borrower_id,event_at,call_id,agent_id,attempt_no,vendor_id,attempt_status
0,ATTEMPT0000001,ACC0009527,BRW0000705,2026-03-10 21:31:13,CALL0019052,AGT0000685,5,VND0000013,FAILED
1,ATTEMPT0000002,ACC0007960,BRW0002732,2026-05-01 20:55:02,CALL0011950,AGT0000472,4,VND0000006,CONNECTED
2,ATTEMPT0000003,ACC0016476,BRW0002174,2026-06-05 20:57:37,CALL0017411,AGT0000035,1,VND0000015,RINGING
3,ATTEMPT0000004,ACC0011111,BRW0003738,2026-05-02 06:08:39,CALL0068999,AGT0000277,3,VND0000010,FAILED
4,ATTEMPT0000005,ACC0010343,BRW0003352,2026-05-27 03:48:23,CALL0049585,AGT0000346,5,VND0000008,CONNECTED



 promises_to_pay


,ptp_id,account_id,borrower_id,event_at,agent_id,promised_amount,promised_date,status,source
0,PTP0000001,ACC0021078,BRW0003789,2026-04-18 21:11:02,AGT0000787,93575.19,2026-05-17 21:11:02,CANCELLED,FIELD
1,PTP0000002,ACC0026620,BRW0010192,2026-07-08 21:49:28,AGT0000763,83558.92,2026-07-25 21:49:28,KEPT,WHATSAPP
2,PTP0000003,ACC0018900,BRW0011197,2026-08-08 08:57:34,AGT0000878,18164.89,2026-09-02 08:57:34,OPEN,SMS
3,PTP0000004,ACC0019107,BRW0009681,2026-01-11 06:04:20,AGT0000535,52829.08,2026-01-24 06:04:20,KEPT,WHATSAPP
4,PTP0000005,ACC0014157,BRW0004907,2026-05-08 01:42:07,AGT0000115,74970.57,2026-05-19 01:42:07,BROKEN,SMS



 calls


,call_id,account_id,borrower_id,event_at,agent_id,campaign_id,direction,vendor_id,call_status,duration_sec,timezone
0,CALL0000001,ACC0011505,BRW0007139,2026-07-15 15:36:22,AGT0000955,CMP0000015,OUTBOUND,VND0000013,NO_ANSWER,601,Asia/Dubai
1,CALL0000002,ACC0002025,BRW0006253,2026-06-10 06:48:27,AGT0000853,CMP0000060,OUTBOUND,VND0000001,ANSWERED,224,Asia/Kolkata
2,CALL0000003,ACC0013375,BRW0007663,2026-04-07 00:35:35,AGT0000525,CMP0000060,OUTBOUND,VND0000008,FAILED,7,Asia/Dubai
3,CALL0000004,ACC0021534,BRW0008873,2026-02-12 14:16:57,AGT0000945,CMP0000060,OUTBOUND,VND0000001,VOICEMAIL,896,Asia/Dubai
4,CALL0000005,ACC0018502,BRW0004996,2026-05-24 15:33:12,AGT0000966,CMP0000053,OUTBOUND,VND0000006,ANSWERED,711,Asia/Kolkata



 complaints


,complaint_id,account_id,borrower_id,event_at,complaint_type,severity,status,source,resolution_at
0,COMPLAINT0000001,ACC0015256,BRW0010194,2026-04-29 16:34:08,DISPUTE,HIGH,CLOSED,FIELD,2026-05-12 16:34:08
1,COMPLAINT0000002,ACC0002310,BRW0009657,2026-06-20 04:52:15,HARASSMENT,MEDIUM,RESOLVED,CALL,2026-06-28 04:52:15
2,COMPLAINT0000003,ACC0002989,BRW0008434,2026-01-29 14:31:42,WRONG_CONTACT,MEDIUM,INVESTIGATING,WHATSAPP,2026-02-07 14:31:42
3,COMPLAINT0000004,ACC0005034,BRW0011197,2026-07-06 03:59:49,DISPUTE,HIGH,INVESTIGATING,EMAIL,2026-07-08 03:59:49
4,COMPLAINT0000005,ACC0017220,BRW0001397,2026-05-30 18:10:30,DND,MEDIUM,RESOLVED,FIELD,2026-06-09 18:10:30



 whatsapp_events


,whatsapp_event_id,account_id,borrower_id,event_at,message_id,event_type,template_code,provider_id
0,WHATSAPP_EVENT0000001,ACC0006134,BRW0007859,2026-02-27 17:49:38,MSG000008171,FAILED,FIELD_VISIT,VND0000008
1,WHATSAPP_EVENT0000002,ACC0027479,BRW0003963,2026-02-09 11:55:18,MSG000000667,FAILED,PTP_01,VND0000003
2,WHATSAPP_EVENT0000003,ACC0008356,BRW0008340,2026-07-08 05:16:13,MSG000023608,DELIVERED,PAYMENT_LINK,VND0000001
3,WHATSAPP_EVENT0000004,ACC0024727,BRW0001572,2026-05-20 19:48:52,MSG000045438,DELIVERED,PAYMENT_LINK,VND0000010
4,WHATSAPP_EVENT0000005,ACC0024918,BRW0003130,2026-01-10 10:37:24,MSG000041041,READ,LEGAL_NOTICE,VND0000015



 account_status_history


,history_id,account_id,borrower_id,event_at,status,changed_by,source,recorded_at
0,HISTORY0000001,ACC0004322,BRW0005490,2026-07-03 04:28:38,WRITEOFF,AGT0000039,CALL,2026-07-03 00:41:54
1,HISTORY0000002,ACC0024644,BRW0005343,2026-07-18 02:03:23,DELINQUENT,AGT0000059,CALL,2026-07-18 22:42:02
2,HISTORY0000003,ACC0020233,BRW0003150,2026-04-15 09:17:47,CLOSED,AGT0000080,PAYMENT,2026-04-15 19:40:51
3,HISTORY0000004,ACC0004384,BRW0008483,2026-01-16 10:52:04,WRITEOFF,SYSTEM,CORE,2026-01-16 23:05:28
4,HISTORY0000005,ACC0022967,BRW0009477,2026-05-22 04:13:04,PTP,AGT0000073,CORE,2026-05-22 07:08:28



 campaigns


,campaign_id,campaign_name,channel,strategy_version,start_at,target_definition,end_at
0,CMP0000001,DIGITAL_FOLLOWUP,FIELD,legacy,2026-02-17 06:56:01,DPD>=30,2026-04-24 06:56:01
1,CMP0000002,BOUNCE,MIXED,v2,2026-04-30 17:51:31,DPD>=60,2026-05-18 17:51:31
2,CMP0000003,30DPD_W1,MIXED,v1,2026-04-11 16:02:51,DPD>=30,2026-05-18 16:02:51
3,CMP0000004,BOUNCE,VOICE,legacy,2026-04-28 06:15:30,DPD>=60,2026-05-29 06:15:30
4,CMP0000005,60DPD_INTENT,WHATSAPP,legacy,2026-05-04 04:16:21,DPD>=60,2026-07-08 04:16:21



 borrowers


,borrower_id,name,phone,email,city,created_at,updated_at,state
0,BRW0001072,Rahul Verma,9.037419e+09,user9183@example.com,Bhubaneswar,2025-09-25 08:02:29,2026-07-25 22:25:48,Odisha
1,BRW0009288,Neha Singh,9.154913e+09,user9581@example.com,Gurugram,2025-06-29 04:32:01,2025-03-04 12:15:30,Haryana
2,BRW0007855,Vikram Shah,9.986755e+09,user19407@example.com,Hyderabad,2025-11-23 20:30:50,2025-01-07 21:07:17,Telangana
3,BRW0005267,Priya Mehta,9.145160e+09,user4619@example.com,Jaipur,2026-05-09 11:34:12,2025-04-24 21:35:48,Rajasthan
4,BRW0005197,Priya Mehta,9.655567e+09,user4597@example.com,Mumbai,2025-02-13 03:53:20,2026-03-29 19:42:02,Maharashtra



 payments


,payment_id,account_id,borrower_id,event_at,payment_reference,amount,payment_status,payment_method,provider_id
0,PAYMENT0000001,ACC0015539,BRW0011363,2026-02-27 01:28:12,TXN0000007457,22433.23,FAILED,CARD,VND0000001
1,PAYMENT0000002,ACC0004445,BRW0011306,2026-07-23 20:25:20,TXN0000030016,23295.11,FAILED,UPI,VND0000004
2,PAYMENT0000003,ACC0003853,BRW0002549,2026-01-11 21:27:46,TXN0000010466,118814.97,FAILED,NACH,VND0000013
3,PAYMENT0000004,ACC0017531,BRW0006618,2026-06-16 02:35:21,TXN0000031781,145082.17,REVERSED,CASH,VND0000013
4,PAYMENT0000005,ACC0001770,BRW0011492,2026-03-03 06:08:23,TXN0000059257,115148.46,SUCCESS,NETBANKING,VND0000013



 vendor_telephony


,vendor_id,vendor_name,vendor_account_id,timezone,status,schema_version
0,VND0000001,Airtel,VAC342762,Asia/Kolkata,INACTIVE,v3
1,VND0000002,Exotel,VAC456766,UTC,INACTIVE,v3
2,VND0000003,Twilio,VAC074211,UTC,INACTIVE,v3
3,VND0000004,Twilio,VAC321507,UTC,ACTIVE,v1
4,VND0000005,Twilio,VAC976733,Asia/Kolkata,ACTIVE,v1



 sms_events


,sms_event_id,account_id,borrower_id,event_at,message_id,event_type,template_code,provider_id
0,SMS_EVENT0000001,ACC0010751,BRW0009574,2026-04-24 20:57:06,SMS000022764,CLICKED,PAYMENT_LINK,VND0000010
1,SMS_EVENT0000002,ACC0005842,BRW0003619,2026-05-24 11:28:20,SMS000015050,DELIVERED,NOTICE,VND0000003
2,SMS_EVENT0000003,ACC0014253,BRW0003018,2026-03-05 20:23:20,SMS000028337,CLICKED,NOTICE,VND0000008
3,SMS_EVENT0000004,ACC0016374,BRW0002587,2026-05-11 04:56:15,SMS000004875,DELIVERED,DUE_REMINDER,VND0000010
4,SMS_EVENT0000005,ACC0000796,BRW0010499,2026-03-24 08:41:53,SMS000008899,SENT,PTP_REMINDER,VND0000007



 agent_sessions


,session_id,agent_id,login_at,channel,device_id,timezone,logout_at
0,SES0000001,AGT0000117,2026-08-06 13:33:27,VOICE,DEV00243,Asia/Kolkata,2026-08-06 18:41:13
1,SES0000002,AGT0000847,2026-05-27 02:02:28,FIELD,DEV01359,UTC,2026-05-27 09:02:31
2,SES0000003,AGT0000989,2026-08-01 20:33:44,FIELD,DEV01432,Asia/Kolkata,2026-08-02 05:53:43
3,SES0000004,AGT0000961,2026-01-13 19:50:52,FIELD,DEV00402,Asia/Kolkata,2026-01-13 22:20:49
4,SES0000005,AGT0000280,2026-03-03 15:05:04,VOICE,DEV01288,UTC,2026-03-03 18:19:09



 agents


,agent_id,employee_code,agent_name,vendor_id,team,status,joined_at,updated_at
0,AGT0000760,EMP00323,Vikram Shah,VND0000012,T3,INACTIVE,2025-06-19 20:30:53,2025-12-11 03:40:22
1,AGT0000171,EMP00079,Pooja Nair,VND0000012,T1,INACTIVE,2025-08-26 11:06:26,2025-10-11 08:30:33
2,AGT0000766,EMP00030,Sneha Das,VND0000002,FIELD,SUSPENDED,2024-05-30 11:23:06,2026-05-16 03:02:02
3,AGT0000031,EMP00334,Aarav Sharma,VND0000007,T1,INACTIVE,2024-10-11 18:58:28,2025-10-16 13:31:21
4,AGT0000669,EMP00014,Aarav Sharma,VND0000001,T3,SUSPENDED,2024-09-01 19:55:06,2026-07-04 03:33:11


In [40]:
for name, df in datasets.items():
    print("---------------------------------")
    print(name)
    print("-------------------------------------")
    print(df.dtypes)

---------------------------------
accounts
-------------------------------------
account_id             object
borrower_id            object
loan_type              object
principal_amount      float64
outstanding_amount    float64
dpd                     int64
risk_segment           object
status                 object
opened_at              object
timezone               object
schema_version         object
dtype: object
---------------------------------
data_dictionary
-------------------------------------
dataset    object
column     object
dtype      object
dtype: object
---------------------------------
call_dispositions
-------------------------------------
disposition_id         object
account_id             object
borrower_id            object
event_at               object
call_id                object
agent_id               object
disposition_code       object
disposition_version    object
dtype: object
---------------------------------
field_visits
----------------------------

In [42]:
for name , df in datasets.items():
    date_columns = [
        col for col in df.columns
        if any(word in col.lower() for word in 
               ["date" , "time" , "timestamp" , "created" , "updated" ])
    ]
    print(f"\n{name}")
    print(date_columns)


accounts
['timezone']

data_dictionary
[]

call_dispositions
[]

field_visits
[]

daily_targeting
['target_date']

call_attempts
[]

promises_to_pay
['promised_date']

calls
['timezone']

complaints
[]

whatsapp_events
[]

account_status_history
[]

campaigns
[]

borrowers
['created_at', 'updated_at']

payments
[]

vendor_telephony
['timezone']

sms_events
[]

agent_sessions
['timezone']

agents
['updated_at']


In [43]:
for name , df in datasets.items():
    missing = df.isnull().sum()

    missing = missing[missing>0].sort_values(ascending = False)

    print("-----------------------")
    print(name)
    print("------------------------")
    display(missing)

-----------------------
accounts
------------------------


borrower_id    455
dtype: int64

-----------------------
data_dictionary
------------------------


Series([], dtype: int64)

-----------------------
call_dispositions
------------------------


Series([], dtype: int64)

-----------------------
field_visits
------------------------


scheduled_at    250
dtype: int64

-----------------------
daily_targeting
------------------------


Series([], dtype: int64)

-----------------------
call_attempts
------------------------


vendor_id    2400
dtype: int64

-----------------------
promises_to_pay
------------------------


Series([], dtype: int64)

-----------------------
calls
------------------------


agent_id    1827
dtype: int64

-----------------------
complaints
------------------------


Series([], dtype: int64)

-----------------------
whatsapp_events
------------------------


Series([], dtype: int64)

-----------------------
account_status_history
------------------------


Series([], dtype: int64)

-----------------------
campaigns
------------------------


Series([], dtype: int64)

-----------------------
borrowers
------------------------


email    895
phone    614
dtype: int64

-----------------------
payments
------------------------


payment_reference    382
dtype: int64

-----------------------
vendor_telephony
------------------------


Series([], dtype: int64)

-----------------------
sms_events
------------------------


Series([], dtype: int64)

-----------------------
agent_sessions
------------------------


Series([], dtype: int64)

-----------------------
agents
------------------------


Series([], dtype: int64)

In [44]:
for name , df in datasets.items():
    print(
        name ,
        "total rows =" , len(df),
        "duplicate rows=" , df.duplicated().sum()
    )

accounts total rows = 30000 duplicate rows= 0
data_dictionary total rows = 143 duplicate rows= 0
call_dispositions total rows = 35000 duplicate rows= 0
field_visits total rows = 25000 duplicate rows= 0
daily_targeting total rows = 45000 duplicate rows= 0
call_attempts total rows = 120000 duplicate rows= 0
promises_to_pay total rows = 18000 duplicate rows= 0
calls total rows = 91350 duplicate rows= 1271
complaints total rows = 8000 duplicate rows= 0
whatsapp_events total rows = 60600 duplicate rows= 600
account_status_history total rows = 60000 duplicate rows= 0
campaigns total rows = 120 duplicate rows= 0
borrowers total rows = 30600 duplicate rows= 600
payments total rows = 25500 duplicate rows= 486
vendor_telephony total rows = 15 duplicate rows= 0
sms_events total rows = 45000 duplicate rows= 0
agent_sessions total rows = 15000 duplicate rows= 0
agents total rows = 30000 duplicate rows= 0


In [46]:
for name , df in datasets.items():
    print("\n" , name)

    for col in df.columns:
        unique_count = df[col].nunique(dropna= False)

        if unique_count == len(df):
            print("Possible unique key : " , col)


 accounts
Possible unique key :  account_id

 data_dictionary

 call_dispositions
Possible unique key :  disposition_id

 field_visits
Possible unique key :  visit_id
Possible unique key :  latitude
Possible unique key :  longitude

 daily_targeting
Possible unique key :  target_id

 call_attempts
Possible unique key :  attempt_id

 promises_to_pay
Possible unique key :  ptp_id

 calls

 complaints
Possible unique key :  complaint_id

 whatsapp_events

 account_status_history
Possible unique key :  history_id

 campaigns
Possible unique key :  campaign_id
Possible unique key :  start_at
Possible unique key :  end_at

 borrowers

 payments

 vendor_telephony
Possible unique key :  vendor_id
Possible unique key :  vendor_account_id

 sms_events
Possible unique key :  sms_event_id

 agent_sessions
Possible unique key :  session_id

 agents


In [47]:
for name , df in datasets.items():
    id_columns = [
        col for col in df.columns
        if "id" in col.lower()
    ]
    print("\n", name)
    print(id_columns)


 accounts
['account_id', 'borrower_id']

 data_dictionary
[]

 call_dispositions
['disposition_id', 'account_id', 'borrower_id', 'call_id', 'agent_id']

 field_visits
['visit_id', 'account_id', 'borrower_id', 'agent_id']

 daily_targeting
['target_id', 'account_id', 'campaign_id']

 call_attempts
['attempt_id', 'account_id', 'borrower_id', 'call_id', 'agent_id', 'vendor_id']

 promises_to_pay
['ptp_id', 'account_id', 'borrower_id', 'agent_id']

 calls
['call_id', 'account_id', 'borrower_id', 'agent_id', 'campaign_id', 'vendor_id']

 complaints
['complaint_id', 'account_id', 'borrower_id']

 whatsapp_events
['whatsapp_event_id', 'account_id', 'borrower_id', 'message_id', 'provider_id']

 account_status_history
['history_id', 'account_id', 'borrower_id']

 campaigns
['campaign_id']

 borrowers
['borrower_id']

 payments
['payment_id', 'account_id', 'borrower_id', 'provider_id']

 vendor_telephony
['vendor_id', 'vendor_account_id']

 sms_events
['sms_event_id', 'account_id', 'borrower_id

In [49]:
payments = datasets["payments"]
accounts = datasets["accounts"]

valid_accounts = set(accounts["account_id"].dropna())

payments["account_id"].isin(valid_accounts).mean()

np.float64(1.0)

In [52]:
for col in payments.columns:
    print(col, "->", payments[col].dtype)

payment_id -> object
account_id -> object
borrower_id -> object
event_at -> object
payment_reference -> object
amount -> float64
payment_status -> object
payment_method -> object
provider_id -> object


In [54]:
payments = datasets["payments"]

payments["event_at"] = pd.to_datetime(
    payments["event_at"],
    errors="coerce"
)

print("Minimum payment date:", payments["event_at"].min())
print("Maximum payment date:", payments["event_at"].max())

print("Missing/invalid event_at:",
      payments["event_at"].isna().sum())

Minimum payment date: 2026-01-01 00:14:40
Maximum payment date: 2026-08-08 23:50:23
Missing/invalid event_at: 0


In [55]:
payments["month"] = payments["event_at"].dt.to_period("M")

payments["month"].value_counts().sort_index()

month
2026-01    3603
2026-02    3238
2026-03    3650
2026-04    3540
2026-05    3558
2026-06    3423
2026-07    3546
2026-08     942
Freq: M, Name: count, dtype: int64

## Payment Date Coverage

The payments dataset contains valid event timestamps from
1 January 2026 to 8 August 2026.

No payment event timestamps failed datetime conversion.

The August 2026 data is partial, covering only the first
8 days of the month. Therefore August should not be directly
compared with complete months for monthly performance analysis
without accounting for the incomplete observation period.

date_checks = {}

for name, df in datasets.items():

    date_columns = [
        col for col in df.columns
        if any(word in col.lower()
               for word in ["date", "time", "timestamp", "created", "updated", "event"])
    ]

    date_checks[name] = date_columns

    print("\n", name, "->", date_columns)

,dataset,rows,columns,duplicate_rows,missing_cells
0,accounts,30000,11,0,455
1,data_dictionary,143,3,0,0
2,call_dispositions,35000,8,0,0
3,field_visits,25000,10,0,250
4,daily_targeting,45000,7,0,0
5,call_attempts,120000,9,0,2400
6,promises_to_pay,18000,9,0,0
7,calls,91350,11,1271,1827
8,complaints,8000,9,0,0
9,whatsapp_events,60600,8,600,0


In [59]:
for name, df in datasets.items():
    print("\n", name)
    for col in df.columns:
        if df[col].nunique(dropna=False) == len(df):
            print("Possible key:", col)


 accounts
Possible key: account_id

 data_dictionary

 call_dispositions
Possible key: disposition_id

 field_visits
Possible key: visit_id
Possible key: latitude
Possible key: longitude

 daily_targeting
Possible key: target_id

 call_attempts
Possible key: attempt_id

 promises_to_pay
Possible key: ptp_id

 calls

 complaints
Possible key: complaint_id

 whatsapp_events

 account_status_history
Possible key: history_id

 campaigns
Possible key: campaign_id
Possible key: start_at
Possible key: end_at

 borrowers

 payments

 vendor_telephony
Possible key: vendor_id
Possible key: vendor_account_id

 sms_events
Possible key: sms_event_id

 agent_sessions
Possible key: session_id

 agents


In [60]:
checks = [
    ("payments", "account_id", "accounts", "account_id"),
    ("payments", "borrower_id", "borrowers", "borrower_id"),
    ("calls", "account_id", "accounts", "account_id"),
    ("calls", "agent_id", "agents", "agent_id"),
    ("call_attempts", "account_id", "accounts", "account_id"),
    ("promises_to_pay", "account_id", "accounts", "account_id"),
    ("field_visits", "account_id", "accounts", "account_id"),
    ("daily_targeting", "account_id", "accounts", "account_id"),
]

for child_table, child_col, parent_table, parent_col in checks:
    child = datasets[child_table]
    parent = datasets[parent_table]

    valid_ids = set(parent[parent_col].dropna())

    match_rate = child[child_col].isin(valid_ids).mean()

    print(
        f"{child_table}.{child_col} -> "
        f"{parent_table}.{parent_col}: "
        f"{match_rate:.2%}"
    )

payments.account_id -> accounts.account_id: 100.00%
payments.borrower_id -> borrowers.borrower_id: 91.85%
calls.account_id -> accounts.account_id: 100.00%
calls.agent_id -> agents.agent_id: 98.00%
call_attempts.account_id -> accounts.account_id: 100.00%
promises_to_pay.account_id -> accounts.account_id: 100.00%
field_visits.account_id -> accounts.account_id: 100.00%
daily_targeting.account_id -> accounts.account_id: 100.00%


In [61]:
for name, df in datasets.items():
    missing = df.isna().sum()
    missing = missing[missing > 0].sort_values(ascending=False)

    if len(missing) > 0:
        print("\n", name)
        print(missing)


 accounts
borrower_id    455
dtype: int64

 field_visits
scheduled_at    250
dtype: int64

 call_attempts
vendor_id    2400
dtype: int64

 calls
agent_id    1827
dtype: int64

 borrowers
email    895
phone    614
dtype: int64

 payments
payment_reference    382
dtype: int64


Missing values are concentrated in relationship and attribution fields.
The most significant issues are missing vendor IDs in call attempts,
missing agent IDs in calls, missing borrower IDs in accounts, and
missing payment references.

No missing values are imputed during profiling.

In [62]:
for name, df in datasets.items():
    dup = df.duplicated().sum()

    if dup > 0:
        print(name, "->", dup, "exact duplicate rows")

calls -> 1271 exact duplicate rows
whatsapp_events -> 600 exact duplicate rows
borrowers -> 600 exact duplicate rows
payments -> 486 exact duplicate rows


Exact duplicate rows were identified in calls, WhatsApp events,
borrowers and payments.

These records have not been removed. Their business-level validity
will be investigated during the data-forensics stage.

## PHASE 2 : Data Forensics

### Step 1: Duplicate Payments

In [64]:
payments = datasets["payments"]

print("Duplicate payment_id:",
      payments["payment_id"].duplicated().sum())

Duplicate payment_id: 500


In [65]:
print(
    payments[payments["payment_id"].duplicated(keep=False)]
    .sort_values("payment_id")
    .head(20)
)

           payment_id  account_id borrower_id            event_at  \
55     PAYMENT0000056  ACC0019495  BRW0009716 2026-02-24 09:33:29   
25035  PAYMENT0000056  ACC0019495  BRW0009716 2026-02-24 09:33:29   
75     PAYMENT0000076  ACC0027928  BRW0010869 2026-02-05 17:14:30   
25408  PAYMENT0000076  ACC0027928  BRW0010869 2026-02-05 17:14:30   
107    PAYMENT0000108  ACC0017047  BRW0009175 2026-06-09 08:17:45   
25481  PAYMENT0000108  ACC0017047  BRW0009175 2026-06-09 08:17:45   
148    PAYMENT0000149  ACC0018444  BRW0005741 2026-07-25 03:04:14   
25099  PAYMENT0000149  ACC0018444  BRW0005741 2026-07-25 03:04:14   
198    PAYMENT0000199  ACC0000056  BRW0001872 2026-05-12 22:49:22   
25330  PAYMENT0000199  ACC0000056  BRW0001872 2026-05-12 22:49:22   
254    PAYMENT0000255  ACC0001307  BRW0001928 2026-05-07 18:37:15   
25201  PAYMENT0000255  ACC0001307  BRW0001928 2026-05-07 18:37:15   
262    PAYMENT0000263  ACC0004813  BRW0004424 2026-02-03 14:14:28   
25430  PAYMENT0000263  ACC0004813 

In [66]:
duplicate_payments = payments[
    payments["payment_id"].duplicated(keep=False)
]

print("Duplicate rows:", len(duplicate_payments))
print("Unique duplicated payment IDs:",
      duplicate_payments["payment_id"].nunique())

Duplicate rows: 1000
Unique duplicated payment IDs: 500


In [67]:
print(
    duplicate_payments.groupby("payment_id").size()
    .value_counts()
    .sort_index()
)

2    500
Name: count, dtype: int64


In [68]:
duplicate_ids = duplicate_payments["payment_id"].unique()

duplicate_amount = payments[
    payments["payment_id"].isin(duplicate_ids)
]["amount"].sum()

print("Amount represented by duplicated rows: ₹", duplicate_amount)

Amount represented by duplicated rows: ₹ 76732688.52


In [69]:
amount_to_remove = duplicate_payments.drop_duplicates(
    subset="payment_id"
)["amount"].sum()

print("Amount from redundant duplicate copies: ₹", amount_to_remove)

Amount from redundant duplicate copies: ₹ 38366344.26


Duplicate payment investigation found 500 unique payment IDs appearing
exactly twice, resulting in 1,000 duplicate rows.

The redundant duplicate copies represent ₹3.84 Cr of payment value.
However, this amount cannot yet be treated as inflated recovery because
payment status must be considered. Only valid successful payments should
contribute to recovery.

In [70]:
payments["payment_status"].value_counts()

payment_status
SUCCESS     17880
FAILED       3744
PENDING      2592
REVERSED     1284
Name: count, dtype: int64

In [71]:
duplicate_success = duplicate_payments[
    duplicate_payments["payment_status"] == "SUCCESS"
]

print("Duplicate SUCCESS rows:", len(duplicate_success))
print("Unique duplicate SUCCESS payment IDs:",
      duplicate_success["payment_id"].nunique())

print("Redundant SUCCESS amount: ₹",
      duplicate_success.drop_duplicates("payment_id")["amount"].sum())

Duplicate SUCCESS rows: 692
Unique duplicate SUCCESS payment IDs: 346
Redundant SUCCESS amount: ₹ 25901961.689999998


### Finding: Duplicate Successful Payments

346 unique payment IDs appear twice in the payments table.
Both copies are marked SUCCESS.

The redundant copies represent ₹2.59 Cr of successful payment value.
Therefore, the raw recovery figure may be overstated by up to ₹2.59 Cr
if both duplicate records are counted.

Treatment: retain one record per payment_id in the Golden Dataset,
subject to further validation of payment references and event history.

In [72]:
print("Duplicate payment_reference:",
      payments["payment_reference"].duplicated().sum())

Duplicate payment_reference: 4678


In [73]:
ref_counts = payments["payment_reference"].value_counts()

print("Unique payment references:",
      payments["payment_reference"].nunique())

print("References appearing more than once:",
      (ref_counts > 1).sum())

print("Most repeated references:")
print(ref_counts[ref_counts > 1].head(10))

Unique payment references: 20821
References appearing more than once: 3745
Most repeated references:
payment_reference
TXN0000002005    5
TXN0000065723    5
TXN0000044312    5
TXN0000006936    5
TXN0000052559    5
TXN0000021482    5
TXN0000050468    5
TXN0000008956    4
TXN0000000776    4
TXN0000027954    4
Name: count, dtype: int64


In [74]:
print("Missing payment_reference:",
      payments["payment_reference"].isna().sum())


Missing payment_reference: 382


### Payment Reference Investigation

3,745 payment references appear more than once, with some references
appearing up to five times. 382 payment records have no payment_reference.

Repeated payment references cannot automatically be classified as
duplicate payments because they may represent retries or different
payment states. Further investigation is required.

In [75]:
ref_status = (
    payments.groupby("payment_reference")["payment_status"]
    .agg(list)
)

print(
    ref_status[
        ref_status.apply(lambda x: len(x) > 1)
    ].head(10)
)

payment_reference
TXN0000000009              [SUCCESS, SUCCESS]
TXN0000000027               [FAILED, SUCCESS]
TXN0000000032     [SUCCESS, PENDING, SUCCESS]
TXN0000000113    [SUCCESS, REVERSED, SUCCESS]
TXN0000000132              [SUCCESS, SUCCESS]
TXN0000000134                [FAILED, FAILED]
TXN0000000154              [SUCCESS, SUCCESS]
TXN0000000186              [SUCCESS, SUCCESS]
TXN0000000196              [SUCCESS, SUCCESS]
TXN0000000212              [SUCCESS, SUCCESS]
Name: payment_status, dtype: object


### Finding: Payment Reference Reuse

Payment references are reused across different payment statuses.
Examples include SUCCESS + SUCCESS, FAILED + SUCCESS,
SUCCESS + PENDING + SUCCESS, and SUCCESS + REVERSED + SUCCESS.

Therefore, payment_reference alone cannot be used as the deduplication key.
Payment status and transaction/event details must also be considered.

In [76]:
cols = [
    "payment_id",
    "account_id",
    "borrower_id",
    "event_at",
    "payment_reference",
    "amount",
    "payment_status",
    "payment_method",
    "provider_id"
]

print(
    duplicate_payments[cols].duplicated().sum()
)

486


### Final Finding: Exact Duplicate Payments

486 payment rows are exact duplicates across all payment fields.
These records represent duplicated copies rather than distinct
payment events.

346 duplicated payment IDs are marked SUCCESS, with ₹2.59 Cr
represented by the redundant copies.

Treatment:
Retain one copy of each exact duplicate payment record in the
Golden Dataset and exclude the redundant copies from recovery
calculations.

### Step 2: Payment Attribution.

In [77]:
print("PAYMENTS")
print(datasets["payments"].columns.tolist())

print("\nDAILY TARGETING")
print(datasets["daily_targeting"].columns.tolist())

print("\nCAMPAIGNS")
print(datasets["campaigns"].columns.tolist())

PAYMENTS
['payment_id', 'account_id', 'borrower_id', 'event_at', 'payment_reference', 'amount', 'payment_status', 'payment_method', 'provider_id', 'month']

DAILY TARGETING
['target_id', 'account_id', 'campaign_id', 'target_date', 'priority', 'recommended_channel', 'status']

CAMPAIGNS
['campaign_id', 'campaign_name', 'channel', 'strategy_version', 'start_at', 'target_definition', 'end_at']
The history saving thread hit an unexpected error (OperationalError('attempt to write a readonly database')).History will not be written to the database.


In [78]:
targeting = datasets["daily_targeting"].copy()

targeting["target_date"] = pd.to_datetime(
    targeting["target_date"],
    errors="coerce"
)

print("Targeting start:", targeting["target_date"].min())
print("Targeting end:", targeting["target_date"].max())
print("Invalid dates:", targeting["target_date"].isna().sum())

Targeting start: 2026-01-01 00:00:00
Targeting end: 2026-08-08 00:00:00
Invalid dates: 0


In [79]:
targeting["account_id"].value_counts().describe()

count    23344.000000
mean         1.927690
std          1.044442
min          1.000000
25%          1.000000
50%          2.000000
75%          2.000000
max          8.000000
Name: count, dtype: float64

### Finding: Multiple Targeting Events

Targeting data covers Jan 1 to Aug 8, 2026 with no invalid dates.
23,344 accounts have targeting records.

Accounts have an average of 1.93 targeting records, with some accounts
having up to 8 targeting events.

Therefore, assigning a payment to the latest campaign by default could
create attribution bias.

In [80]:
campaign_per_account = (
    targeting.groupby("account_id")["campaign_id"]
    .nunique()
)

print(campaign_per_account.describe())

count    23344.000000
mean         1.915481
std          1.032983
min          1.000000
25%          1.000000
50%          2.000000
75%          2.000000
max          8.000000
Name: campaign_id, dtype: float64


In [81]:
print(
    "Accounts with multiple campaigns:",
    (campaign_per_account > 1).sum()
)

Accounts with multiple campaigns: 13235


### Finding: Campaign Attribution Risk

13,235 of 23,344 targeted accounts were associated with multiple
campaigns (~56.7%).

Therefore, attributing a payment to the latest campaign alone could
misrepresent campaign performance.

A time-based attribution window is required.

In [87]:
payments["event_at"] = pd.to_datetime(payments["event_at"])
targeting["target_date"] = pd.to_datetime(targeting["target_date"])

payment_target = payments.merge(
    targeting[["account_id", "campaign_id", "target_date"]],
    on="account_id",
    how="left"
)

payment_target["days_after_target"] = (
    payment_target["event_at"].dt.normalize()
    - payment_target["target_date"]
).dt.days

print(payment_target["days_after_target"].describe())

count    38194.000000
mean        -0.049484
std         89.927703
min       -219.000000
25%        -65.000000
50%         -1.000000
75%         65.000000
max        218.000000
Name: days_after_target, dtype: float64


A negative value means the payment happened before the targeting event.

But there's an important issue: our merge matched every payment with every targeting record for that account, so this distribution includes many irrelevant campaign-targeting events.

In [86]:
targeting = targeting.copy()
payments = payments.copy()

targeting["target_date"] = pd.to_datetime(targeting["target_date"])
payments["event_at"] = pd.to_datetime(payments["event_at"])

# Remove missing keys just in case
targeting = targeting.dropna(subset=["account_id", "target_date"])
payments = payments.dropna(subset=["account_id", "event_at"])

# Sort primarily by the time column
targeting = targeting.sort_values(["target_date", "account_id"])
payments = payments.sort_values(["event_at", "account_id"])

payment_target = pd.merge_asof(
    payments,
    targeting[["account_id", "campaign_id", "target_date"]],
    left_on="event_at",
    right_on="target_date",
    by="account_id",
    direction="backward"
)

payment_target["days_after_target"] = (
    payment_target["event_at"].dt.normalize()
    - payment_target["target_date"]
).dt.days

print(payment_target["days_after_target"].describe())

count    12286.000000
mean        56.969640
std         46.335022
min          0.000000
25%         19.000000
50%         45.000000
75%         85.000000
max        218.000000
Name: days_after_target, dtype: float64


In [88]:
for days in [7, 14, 30, 60, 90]:
    count = (payment_target["days_after_target"] <= days).sum()
    print(f"{days} days: {count} payments")

7 days: 20502 payments
14 days: 21652 payments
30 days: 24112 payments
60 days: 28172 payments
90 days: 31519 payments


In [89]:
print(payment_target["days_after_target"].notna().sum())

38194


In [90]:
for days in [7, 14, 30, 60, 90]:
    count = (
        payment_target["days_after_target"].notna()
        & (payment_target["days_after_target"] <= days)
    ).sum()
    print(f"{days} days: {count} payments")

7 days: 20502 payments
14 days: 21652 payments
30 days: 24112 payments
60 days: 28172 payments
90 days: 31519 payments


ISSUE : . Our payment_target has 38,194 rows, not 25,500, because merge_asof is still matching multiple rows for some accounts.

In [93]:
targeting = targeting.drop_duplicates(
    subset=["account_id", "target_date", "campaign_id"]
)

targeting = targeting.sort_values(
    ["target_date", "account_id"]
)

payments = payments.sort_values(
    ["event_at", "account_id"]
)

payment_target = pd.merge_asof(
    payments,
    targeting[["account_id", "campaign_id", "target_date"]],
    left_on="event_at",
    right_on="target_date",
    by="account_id",
    direction="backward"
)

print("Payments:", len(payments))
print("Matched rows:", len(payment_target))

Payments: 25500
Matched rows: 25500


In [94]:
payment_target["days_after_target"] = (
    payment_target["event_at"].dt.normalize()
    - payment_target["target_date"]
).dt.days

print(payment_target["days_after_target"].describe())

count    12286.000000
mean        56.969640
std         46.335022
min          0.000000
25%         19.000000
50%         45.000000
75%         85.000000
max        218.000000
Name: days_after_target, dtype: float64


In [95]:
matched = payment_target[
    payment_target["days_after_target"].notna()
]

for days in [7, 14, 30, 60, 90]:
    count = (matched["days_after_target"] <= days).sum()
    print(f"{days} days: {count} payments")

7 days: 1338 payments
14 days: 2392 payments
30 days: 4515 payments
60 days: 7515 payments
90 days: 9505 payments


### Attribution Window Sensitivity

Among 12,286 payments with a prior targeting event:

7-day window: 1,338 payments
14-day window: 2,392 payments
30-day window: 4,515 payments
60-day window: 7,515 payments
90-day window: 9,505 payments

Campaign attribution is therefore highly sensitive to the chosen
attribution window. A single "latest campaign" attribution rule could
materially change reported campaign performance.

In [96]:
print(datasets["promises_to_pay"].columns.tolist())

['ptp_id', 'account_id', 'borrower_id', 'event_at', 'agent_id', 'promised_amount', 'promised_date', 'status', 'source']


In [97]:
ptp = datasets["promises_to_pay"].copy()

ptp["event_at"] = pd.to_datetime(ptp["event_at"])
ptp["promised_date"] = pd.to_datetime(ptp["promised_date"])

print("PTP event start:", ptp["event_at"].min())
print("PTP event end:", ptp["event_at"].max())
print("PTP statuses:")
print(ptp["status"].value_counts())


PTP event start: 2026-01-01 00:24:14
PTP event end: 2026-08-08 23:59:33
PTP statuses:
status
BROKEN       4553
CANCELLED    4543
KEPT         4489
OPEN         4415
Name: count, dtype: int64


### PTP Profile

PTP events cover Jan 1 to Aug 8, 2026.

PTP statuses:
KEPT: 4,489
BROKEN: 4,553
CANCELLED: 4,543
OPEN: 4,415

PTP status must be considered when linking PTP activity to
subsequent recovery. A PTP event alone does not represent a
successful collection.

In [100]:
ptp = ptp.sort_values(["event_at", "account_id"])
payments = payments.sort_values(["event_at", "account_id"])

payment_ptp = pd.merge_asof(
    payments,
    ptp[["account_id", "ptp_id", "event_at", "status", "promised_amount"]],
    left_on="event_at",
    right_on="event_at",
    by="account_id",
    direction="backward",
    suffixes=("_payment", "_ptp")
)

print("Payments:", len(payments))
print("Matched rows:", len(payment_ptp))
print(payment_ptp["status"].value_counts(dropna=False))

Payments: 25500
Matched rows: 25500
status
NaN          19254
BROKEN        1609
CANCELLED     1556
KEPT          1552
OPEN          1529
Name: count, dtype: int64


In [102]:
print(payment_ptp.columns.tolist())

['payment_id', 'account_id', 'borrower_id', 'event_at', 'payment_reference', 'amount', 'payment_status', 'payment_method', 'provider_id', 'month', 'ptp_id', 'status', 'promised_amount']


In [105]:
ptp2 = ptp.rename(columns={"event_at": "ptp_event_at"}).copy()

payments2 = payments.rename(columns={"event_at": "payment_event_at"}).copy()

ptp2 = ptp2.sort_values(["ptp_event_at", "account_id"])
payments2 = payments2.sort_values(["payment_event_at", "account_id"])

payment_ptp = pd.merge_asof(
    payments2,
    ptp2[[
        "account_id",
        "ptp_id",
        "ptp_event_at",
        "status",
        "promised_amount"
    ]],
    left_on="payment_event_at",
    right_on="ptp_event_at",
    by="account_id",
    direction="backward"
)

payment_ptp["days_after_ptp"] = (
    payment_ptp["payment_event_at"].dt.normalize()
    - payment_ptp["ptp_event_at"].dt.normalize()
).dt.days

print(payment_ptp["days_after_ptp"].describe())

count    6246.000000
mean       65.632885
std        49.431829
min         0.000000
25%        24.000000
50%        55.000000
75%        99.000000
max       215.000000
Name: days_after_ptp, dtype: float64


### PTP-to-Payment Timing

6,246 payments had a previous PTP event for the same account.
The median gap between PTP and payment was 55 days.
The 25th percentile was 24 days and the 75th percentile was 99 days.

This indicates that payment attribution is sensitive to the chosen
time window and should not be based solely on the latest interaction.

In [106]:
print(
    payment_ptp[payment_ptp["status"].notna()]
    ["status"]
    .value_counts()
)

status
BROKEN       1609
CANCELLED    1556
KEPT         1552
OPEN         1529
Name: count, dtype: int64


In [107]:
kept = payment_ptp[
    payment_ptp["status"] == "KEPT"
]

print("Payments after KEPT PTP:", len(kept))
print("Total amount:", kept["amount"].sum())

Payments after KEPT PTP: 1552
Total amount: 118871553.84


### Finding: Payments After Kept PTP

1,552 payments occurred after a KEPT PTP event.
The associated payment amount is ₹11.89 Cr.

This is an observed temporal relationship, not proof of causal
attribution. Final attribution rules will be defined after comparing
other interaction types and time windows.

In [108]:
kept["payment_status"].value_counts()

payment_status
SUCCESS     1128
FAILED       222
PENDING      136
REVERSED      66
Name: count, dtype: int64

### Finding: Successful Payments After Kept PTP

Among 1,552 payments following a KEPT PTP:
- 1,128 were SUCCESS
- 222 were FAILED
- 136 were PENDING
- 66 were REVERSED

Therefore, payment_status must be used when calculating recovery.
A payment following a PTP should not automatically be counted as
successful recovery.

In [109]:
kept_success = kept[
    kept["payment_status"] == "SUCCESS"
]

print("Successful payments:", len(kept_success))
print("Successful recovery amount: ₹",
      kept_success["amount"].sum())

Successful payments: 1128
Successful recovery amount: ₹ 85712786.26


### Successful Recovery After Kept PTP

1,128 successful payments occurred after a KEPT PTP,
representing ₹8.57 Cr in payment value.

Only SUCCESS payments are included as recovery.

In [111]:
kept_success = kept[
    kept["payment_status"] == "SUCCESS"
].copy()

kept_success["payment_vs_promised"] = (
    kept_success["amount"] / kept_success["promised_amount"]
)

print(kept_success["payment_vs_promised"].describe())

count    1128.000000
mean        3.948906
std        10.297215
min         0.002053
25%         0.729493
50%         1.576630
75%         2.897283
max       177.089032
Name: payment_vs_promised, dtype: float64


In [112]:
kept_success[
    kept_success["payment_vs_promised"] > 10
][[
    "account_id",
    "ptp_id",
    "promised_amount",
    "amount",
    "payment_status",
    "payment_event_at",
    "ptp_event_at",
    "payment_vs_promised"
]].sort_values(
    "payment_vs_promised",
    ascending=False
).head(10)

,account_id,ptp_id,promised_amount,amount,payment_status,payment_event_at,ptp_event_at,payment_vs_promised
9529,ACC0007257,PTP0009053,671.67,118945.39,SUCCESS,2026-03-23 11:58:38,2026-01-26 15:10:08,177.089032
23772,ACC0015156,PTP0006572,1194.33,137603.03,SUCCESS,2026-07-24 23:21:48,2026-07-21 20:47:47,115.213576
19276,ACC0006012,PTP0000407,1071.02,98061.25,SUCCESS,2026-06-15 15:55:44,2026-03-12 04:50:36,91.558748
15121,ACC0003321,PTP0007450,1281.55,104438.24,SUCCESS,2026-05-10 17:12:46,2026-05-05 14:55:18,81.493691
24076,ACC0004512,PTP0006344,1088.62,85872.99,SUCCESS,2026-07-27 14:04:15,2026-06-17 20:03:42,78.882429
21678,ACC0004512,PTP0006344,1088.62,80258.44,SUCCESS,2026-07-07 00:35:28,2026-06-17 20:03:42,73.724936
12142,ACC0011590,PTP0000383,2239.92,142612.06,SUCCESS,2026-04-14 23:26:42,2026-03-24 00:35:35,63.668372
12657,ACC0029183,PTP0002230,695.90,43340.89,SUCCESS,2026-04-19 09:30:32,2026-01-20 21:29:36,62.280342
25369,ACC0020346,PTP0005670,2226.07,136294.98,SUCCESS,2026-08-07 22:32:09,2026-03-16 17:23:52,61.226727
21715,ACC0003321,PTP0007450,1281.55,75968.53,SUCCESS,2026-07-07 06:30:39,2026-05-05 14:55:18,59.278631


In [113]:
print(kept_success.columns.tolist())

['payment_id', 'account_id', 'borrower_id', 'payment_event_at', 'payment_reference', 'amount', 'payment_status', 'payment_method', 'provider_id', 'month', 'ptp_id', 'ptp_event_at', 'status', 'promised_amount', 'days_after_ptp', 'payment_vs_promised']


### Finding: PTP Matching Anomalies

Several successful payments following KEPT PTPs are substantially larger
than the promised amount. Some PTPs are also associated with multiple
subsequent payments.

Therefore, a simple latest-PTP-to-payment join can overstate PTP-attributed
recovery. PTP attribution requires additional rules around timing,
multiple payments and promised amounts.

In [114]:
print(
    kept_success["ptp_id"].value_counts().head(10)
)

ptp_id
PTP0011079    4
PTP0002515    4
PTP0001608    4
PTP0012038    4
PTP0013837    3
PTP0000502    3
PTP0014818    3
PTP0014645    3
PTP0017923    3
PTP0008733    3
Name: count, dtype: int64


### Finding: Multiple Payments Per PTP

Several KEPT PTP IDs are associated with multiple successful payments,
with some PTPs linked to up to four payments.

Therefore, PTP attribution should not automatically assign all later
payments to a single PTP. A defined attribution window and payment
allocation rule are required.

In [115]:
ptp_payment_counts = kept_success.groupby("ptp_id").size()

print("PTPs with multiple successful payments:",
      (ptp_payment_counts > 1).sum())

print("Total PTPs with successful payments:",
      ptp_payment_counts.size)

PTPs with multiple successful payments: 166
Total PTPs with successful payments: 928


### Finding: Multiple Successful Payments Per PTP

928 KEPT PTPs are associated with at least one successful payment.
166 PTPs (17.9%) are associated with multiple successful payments.

Therefore, all subsequent payments should not automatically be attributed
to a single PTP. A defined attribution window and allocation rule are
required.

In [116]:
calls = datasets["calls"]

print("Total calls:", len(calls))
print("Missing agent_id:", calls["agent_id"].isna().sum())
print("Unique agent IDs:", calls["agent_id"].nunique())

Total calls: 91350
Missing agent_id: 1827
Unique agent IDs: 1000


### Finding: Agent Identity

The calls table contains 91,350 records and 1,827 calls have a missing
agent_id (2%). There are 1,000 unique agent IDs among the calls.

Missing and potentially inconsistent agent identities may affect
agent-level performance analysis.



In [119]:
agents = datasets["agents"]

print("Agents table rows:", len(agents))
print("Unique agent IDs:", agents["agent_id"].nunique())
print("Missing agent IDs:", agents["agent_id"].isna().sum())

Agents table rows: 30000
Unique agent IDs: 1000
Missing agent IDs: 0


In [120]:
print(agents.columns.tolist())

['agent_id', 'employee_code', 'agent_name', 'vendor_id', 'team', 'status', 'joined_at', 'updated_at']


### Finding: Agent Master History

The agents table contains 30,000 records but only 1,000 unique agent IDs.
This indicates multiple records per agent and suggests that the table may
contain historical or changing agent attributes.

Agent identity should therefore be resolved using agent_id together with
employee/vendor information and effective dates rather than assuming
one row per agent.

In [124]:
agents.groupby("agent_id").size().describe()


count    1000.000000
mean       30.000000
std         5.570011
min        14.000000
25%        26.000000
50%        30.000000
75%        34.000000
max        48.000000
dtype: float64

In [125]:
agents.groupby("agent_id")["employee_code"].nunique().describe()

count    1000.000000
mean       29.604000
std         5.461044
min        14.000000
25%        26.000000
50%        29.000000
75%        33.000000
max        48.000000
Name: employee_code, dtype: float64

### Finding: Agent Historical Records

Each agent_id appears across multiple records in the agents table
(mean ≈ 30 records per agent).

Agent IDs also have multiple employee_code values, indicating that
agent attributes/identifiers change over time.

Therefore, agent-level analysis requires an effective-date approach
rather than a simple join to the agents table.

In [126]:
for col in ["employee_code", "vendor_id", "team", "status"]:
    print("\n", col)
    print(
        agents.groupby("agent_id")[col]
        .nunique()
        .describe()
    )


 employee_code
count    1000.000000
mean       29.604000
std         5.461044
min        14.000000
25%        26.000000
50%        29.000000
75%        33.000000
max        48.000000
Name: employee_code, dtype: float64

 vendor_id
count    1000.000000
mean       13.006000
std         1.318978
min         7.000000
25%        12.000000
50%        13.000000
75%        14.000000
max        15.000000
Name: vendor_id, dtype: float64

 team
count    1000.000000
mean        4.990000
std         0.099549
min         4.000000
25%         5.000000
50%         5.000000
75%         5.000000
max         5.000000
Name: team, dtype: float64

 status
count    1000.0
mean        3.0
std         0.0
min         3.0
25%         3.0
50%         3.0
75%         3.0
max         3.0
Name: status, dtype: float64


### Finding: Agent Attribute Changes

Agent attributes vary over time. Employee codes and vendor IDs show
multiple values per agent, while team is mostly stable and status has
three distinct values per agent.

Agent-level joins must therefore consider the effective time of the
agent record to avoid assigning calls to the wrong vendor or employee
identity.

In [128]:
agents["updated_at"] = pd.to_datetime(
    agents["updated_at"],
    errors="coerce"
)

print(agents["updated_at"].min())
print(agents["updated_at"].max())
print(agents["updated_at"].isna().sum())
print(agents["joined_at"].min())
print(agents["joined_at"].max())

2025-01-01 00:57:32
2026-08-03 23:45:38
0
2024-01-01 00:10:05
2025-11-30 23:23:30


### Finding: Agent Effective Dates

Agent records contain historical timestamps. joined_at ranges from
Jan 2024 to Nov 2025, while updated_at ranges from Jan 2025 to
Aug 3, 2026 with no missing values.

These timestamps can support time-aware agent/vendor mapping.

In [129]:
employee_agent = agents.groupby("employee_code")["agent_id"].nunique()

print("Employee codes:", employee_agent.size)
print("Employee codes linked to multiple agents:",
      (employee_agent > 1).sum())

Employee codes: 1099
Employee codes linked to multiple agents: 1099


### Finding: Employee Code Is Not a Unique Identifier

There are 1,099 employee codes, and every employee code is associated
with multiple agent IDs.

Therefore, employee_code cannot be used as the primary agent identifier.
Agent identity should be based on agent_id, with employee/vendor mappings
resolved using historical dates.

In [130]:
vendor_agent = agents.groupby("vendor_id")["agent_id"].nunique()

print("Vendors:", vendor_agent.size)
print("Agents per vendor:")
print(vendor_agent.describe())

Vendors: 15
Agents per vendor:
count     15.000000
mean     867.066667
std        7.759480
min      850.000000
25%      862.000000
50%      868.000000
75%      870.500000
max      880.000000
Name: agent_id, dtype: float64


In [131]:
print(vendor_agent.sort_values(ascending=False).head(10))

vendor_id
VND0000014    880
VND0000004    876
VND0000001    876
VND0000013    871
VND0000011    870
VND0000006    870
VND0000010    869
VND0000008    868
VND0000005    868
VND0000012    866
Name: agent_id, dtype: int64


### Finding: Vendor Mapping

The agents table contains 15 vendors, with approximately 850–880 agents
per vendor.

Vendor IDs therefore provide a stable higher-level grouping, while
agent_id should remain the primary identifier for agent-level analysis.
Historical dates are required when analyzing vendor attribution over time.

In [132]:
print(calls.columns.tolist())

['call_id', 'account_id', 'borrower_id', 'event_at', 'agent_id', 'campaign_id', 'direction', 'vendor_id', 'call_status', 'duration_sec', 'timezone']


In [133]:
call_agent_vendor = calls[
    calls["agent_id"].notna()
].merge(
    agents[["agent_id", "vendor_id"]].drop_duplicates("agent_id"),
    on="agent_id",
    how="left",
    suffixes=("_call", "_agent")
)

print("Calls with agent match:", len(call_agent_vendor))

print(
    "Vendor mismatches:",
    (
        call_agent_vendor["vendor_id_call"]
        != call_agent_vendor["vendor_id_agent"]
    ).sum()
)

print(
    "Calls with agent_id but no agents match:",
    call_agent_vendor["vendor_id_agent"].isna().sum()
)

Calls with agent match: 89523
Vendor mismatches: 83721
Calls with agent_id but no agents match: 0


In [135]:
agent_vendor_counts = (
    agents.groupby("agent_id")["vendor_id"]
    .nunique()
)

print("Agents with multiple vendors:",
      (agent_vendor_counts > 1).sum())

print("Total agents:",
      agent_vendor_counts.size)
print(
    agent_vendor_counts.value_counts().sort_index()
)

Agents with multiple vendors: 1000
Total agents: 1000
vendor_id
7       1
8       3
9       7
10     25
11     91
12    184
13    316
14    250
15    123
Name: count, dtype: int64


### Finding: Historical Vendor Changes

All 1,000 agent IDs are associated with multiple vendor IDs over time.
Therefore, vendor_id must be resolved using the agent record effective at
the time of the call. A simple agent_id → vendor_id lookup would produce
incorrect vendor attribution.

In [136]:
agent_dates = agents.sort_values(
    ["agent_id", "updated_at"]
)

agent_dates["next_updated_at"] = (
    agent_dates.groupby("agent_id")["updated_at"].shift(-1)
)

print(
    (agent_dates["next_updated_at"] <= agent_dates["updated_at"])
    .sum()
)


0


In [137]:
print(
    agent_dates[
        ["agent_id", "employee_code", "vendor_id",
         "joined_at", "updated_at"]
    ].head(10)
)

         agent_id employee_code   vendor_id            joined_at  \
9554   AGT0000001      EMP00883  VND0000010  2025-09-15 12:18:43   
3016   AGT0000001      EMP00285  VND0000013  2025-05-02 11:13:31   
18301  AGT0000001      EMP00191  VND0000015  2025-11-04 07:01:56   
21572  AGT0000001      EMP00745  VND0000008  2024-02-08 16:05:41   
8967   AGT0000001      EMP01082  VND0000013  2025-05-02 01:36:54   
6520   AGT0000001      EMP00632  VND0000007  2024-08-02 00:51:56   
19963  AGT0000001      EMP00903  VND0000002  2024-02-21 17:11:06   
9420   AGT0000001      EMP00723  VND0000013  2025-03-04 14:23:32   
25883  AGT0000001      EMP00404  VND0000014  2025-11-13 07:54:11   
15127  AGT0000001      EMP00227  VND0000007  2024-12-06 13:45:28   

               updated_at  
9554  2025-02-08 10:18:20  
3016  2025-02-14 12:38:08  
18301 2025-03-09 16:24:54  
21572 2025-03-09 22:26:39  
8967  2025-04-25 02:56:44  
6520  2025-08-30 06:00:31  
19963 2025-09-18 08:17:45  
9420  2025-10-11 06:30:44  

In [138]:
invalid_agent_dates = agents[
    agents["joined_at"] > agents["updated_at"]
]

print("joined_at > updated_at:", len(invalid_agent_dates))

joined_at > updated_at: 4078


In [139]:
print(
    invalid_agent_dates[
        ["agent_id", "employee_code", "vendor_id",
         "joined_at", "updated_at"]
    ].head(10)
)

      agent_id employee_code   vendor_id            joined_at  \
5   AGT0000968      EMP00060  VND0000012  2025-04-30 13:05:13   
24  AGT0000984      EMP01091  VND0000002  2025-09-30 19:06:16   
28  AGT0000123      EMP00735  VND0000003  2025-09-22 11:35:17   
29  AGT0000448      EMP00668  VND0000010  2025-08-15 06:39:47   
31  AGT0001000      EMP00596  VND0000001  2025-04-19 05:42:52   
32  AGT0000556      EMP00707  VND0000011  2025-07-31 02:33:49   
41  AGT0000462      EMP01003  VND0000005  2025-09-14 07:56:15   
42  AGT0000221      EMP00778  VND0000007  2025-05-31 05:07:48   
53  AGT0000633      EMP00927  VND0000010  2025-08-25 01:05:55   
58  AGT0000502      EMP00313  VND0000007  2025-10-03 09:24:08   

            updated_at  
5  2025-02-11 19:01:45  
24 2025-03-12 14:06:00  
28 2025-07-14 09:18:01  
29 2025-04-27 12:16:49  
31 2025-01-25 18:08:59  
32 2025-03-25 11:03:56  
41 2025-06-11 07:31:47  
42 2025-03-31 11:01:50  
53 2025-05-21 11:28:25  
58 2025-09-03 17:38:32  


### Finding: Invalid Agent Dates

4,078 of 30,000 agent records have joined_at later than updated_at
(~13.6%).

Therefore, joined_at and updated_at cannot be directly treated as
effective start/end dates for historical agent attribution.
Vendor and agent history requires additional validation before use.

In [140]:
invalid_agent_dates["vendor_id"].value_counts()

vendor_id
VND0000004    303
VND0000012    296
VND0000008    295
VND0000010    288
VND0000006    279
VND0000007    277
VND0000009    271
VND0000011    264
VND0000001    262
VND0000003    262
VND0000002    260
VND0000015    256
VND0000005    255
VND0000013    255
VND0000014    255
Name: count, dtype: int64

In [141]:
invalid_agent_dates["status"].value_counts()

status
INACTIVE     1379
SUSPENDED    1370
ACTIVE       1329
Name: count, dtype: int64

### Finding: Invalid Agent Dates Are Widespread

The 4,078 invalid agent records are distributed across all 15 vendors
and across ACTIVE, INACTIVE, and SUSPENDED statuses.

Therefore, the issue is systemic rather than isolated to a specific
vendor or agent status. Historical agent/vendor attribution should
not rely directly on joined_at and updated_at.

## Payment ↔ Borrower consistency

In [144]:
borrowers = datasets["borrowers"]

match_rate = payments["borrower_id"].isin(
    borrowers["borrower_id"]
).mean()

print("Borrower match rate:", match_rate)

missing_borrowers = payments[
    ~payments["borrower_id"].isin(borrowers["borrower_id"])
]

print("Unmatched payment borrowers:", len(missing_borrowers))

Borrower match rate: 0.9185098039215687
Unmatched payment borrowers: 2078


### Finding: Payment-Borrower Referential Integrity

91.85% of payment borrower_ids match the borrowers table.
2,078 payment records (8.15%) have borrower_ids with no matching
borrower master record.

This can affect borrower-level recovery analysis and borrower
segmentation. These records should not be silently dropped; they
require an explicit treatment in the Golden Dataset.

In [145]:
missing_borrowers["payment_status"].value_counts()

payment_status
SUCCESS     1476
FAILED       287
PENDING      202
REVERSED     113
Name: count, dtype: int64

In [146]:
print(
    missing_borrowers.groupby("payment_status")["amount"]
    .agg(["count", "sum"])
)

                count           sum
payment_status                     
FAILED            287  2.064909e+07
PENDING           202  1.648276e+07
REVERSED          113  8.852338e+06
SUCCESS          1476  1.106785e+08


### Finding: Unmatched Successful Payments

2,078 payment records have no matching borrower master record.
1,476 of these are SUCCESS payments, representing approximately
₹11.07 Cr.

Therefore, borrower-level recovery analysis may exclude or misclassify
a material amount of successful payment value unless unmatched
borrowers are explicitly handled.

In [147]:
print("Unique unmatched borrower IDs:",
      missing_borrowers["borrower_id"].nunique())

print(
    missing_borrowers["borrower_id"]
    .value_counts()
    .head(10)
)

Unique unmatched borrower IDs: 846
borrower_id
BRW0011790    8
BRW0009875    7
BRW0002244    7
BRW0000515    7
BRW0009520    7
BRW0006737    7
BRW0011403    7
BRW0001567    6
BRW0011934    6
BRW0009996    6
Name: count, dtype: int64


### Finding: Unmatched Borrower IDs

2,078 payment records contain 846 unique borrower IDs that do not
exist in the borrowers table.

Some unmatched borrower IDs occur multiple times, indicating that
the issue affects repeated payment activity rather than isolated
records.

This requires explicit treatment before borrower-level recovery
metrics are finalized.

In [148]:
accounts = datasets["accounts"]

account_borrower = accounts[
    ["account_id", "borrower_id"]
].drop_duplicates()

recovered_borrowers = missing_borrowers.merge(
    account_borrower,
    on="account_id",
    how="left",
    suffixes=("_payment", "_account")
)

print(
    "Unmatched payments with account borrower:",
    recovered_borrowers["borrower_id_account"].notna().sum()
)

Unmatched payments with account borrower: 2034


In [149]:
print(
    "Payment borrower differs from account borrower:",
    (
        recovered_borrowers["borrower_id_payment"].notna()
        & recovered_borrowers["borrower_id_account"].notna()
        & (
            recovered_borrowers["borrower_id_payment"]
            != recovered_borrowers["borrower_id_account"]
        )
    ).sum()
)

Payment borrower differs from account borrower: 2034


### Finding: Payment vs Account Borrower Conflict

2,034 unmatched payment records can be linked to a borrower through
the accounts table, but in every case the payment borrower_id differs
from the account borrower_id.

Therefore, the account borrower_id cannot be blindly used to repair
the payment borrower relationship. These conflicts require explicit
data-quality treatment and should be flagged rather than silently
overwritten.

In [150]:
conflicts = recovered_borrowers[
    recovered_borrowers["borrower_id_account"].notna()
    & (
        recovered_borrowers["borrower_id_payment"]
        != recovered_borrowers["borrower_id_account"]
    )
]

print(
    conflicts["payment_status"].value_counts()
)

payment_status
SUCCESS     1448
FAILED       280
PENDING      194
REVERSED     112
Name: count, dtype: int64


In [151]:
print(
    conflicts.groupby("payment_status")["amount"]
    .agg(["count", "sum"])
)


                count           sum
payment_status                     
FAILED            280  2.020664e+07
PENDING           194  1.587829e+07
REVERSED          112  8.831220e+06
SUCCESS          1448  1.085128e+08


### Finding: Conflicting Borrower Identity

2,034 payment records have borrower IDs that conflict with the
borrower ID stored in the accounts table.

1,448 of these are SUCCESS payments, representing approximately
₹10.85 Cr.

The account-level borrower ID should not be used to silently overwrite
the payment borrower ID. These records should be flagged for
reconciliation before borrower-level recovery metrics are finalized.

In [152]:
print(
    payments.groupby("payment_status")["amount"]
    .agg(["count", "sum"])
)

                count           sum
payment_status                     
FAILED           3744  2.835063e+08
PENDING          2592  1.948680e+08
REVERSED         1284  9.739842e+07
SUCCESS         17880  1.341486e+09


### Payment Recovery Baseline

Total payments: 25,500

SUCCESS: 17,880 payments — ₹134.15 Cr
FAILED: 3,744 payments — ₹28.35 Cr
PENDING: 2,592 payments — ₹19.49 Cr
REVERSED: 1,284 payments — ₹9.74 Cr

SUCCESS payments are treated as realized recovery, while FAILED,
PENDING, and REVERSED payments are excluded from realized recovery.

In [153]:
payments_clean = payments.drop_duplicates(
    subset=["payment_id"],
    keep="first"
).copy()

print("Original rows:", len(payments))
print("After payment_id deduplication:", len(payments_clean))

print(
    payments_clean.groupby("payment_status")["amount"]
    .agg(["count", "sum"])
)

Original rows: 25500
After payment_id deduplication: 25000
                count           sum
payment_status                     
FAILED           3677  2.784186e+08
PENDING          2535  1.902232e+08
REVERSED         1254  9.466657e+07
SUCCESS         17534  1.315584e+09


### Payment Deduplication Impact

Removing 500 duplicate payment_id records reduces the payment dataset
from 25,500 to 25,000 records.

Clean SUCCESS payments: 17,534
Clean SUCCESS recovery: ₹131.56 Cr

The deduplicated payment dataset will be used as the baseline for
recovery analytics.

## Phase 3 — Golden Dataset / Cleaning.

## 1: Payments table 

In [154]:
payments_clean = payments.drop_duplicates(
    subset=["payment_id"],
    keep="first"
).copy()

print("Original:", len(payments))
print("Clean:", len(payments_clean))
print("Duplicates removed:", len(payments) - len(payments_clean))

Original: 25500
Clean: 25000
Duplicates removed: 500


In [155]:
print(
    "Duplicate payment IDs:",
    payments_clean["payment_id"].duplicated().sum()
)

Duplicate payment IDs: 0


In [156]:
payments_clean["event_at"] = pd.to_datetime(
    payments_clean["event_at"],
    errors="coerce"
)

print("Invalid payment dates:",
      payments_clean["event_at"].isna().sum())

Invalid payment dates: 0


In [157]:
import os

os.makedirs("../data/processed", exist_ok=True)

In [158]:
payments_clean.to_csv(
    "../data/processed/payments_clean.csv",
    index=False
)

## 2: Borrowers Table

In [159]:
borrowers = datasets["borrowers"].copy()

print("Original rows:", len(borrowers))
print("Duplicate rows:", borrowers.duplicated().sum())
print("Duplicate borrower IDs:", borrowers["borrower_id"].duplicated().sum())

Original rows: 30600
Duplicate rows: 600
Duplicate borrower IDs: 19585


In [160]:
borrowers_clean = borrowers.drop_duplicates().copy()

print("Rows after exact deduplication:", len(borrowers_clean))
print(
    "Duplicate borrower IDs remaining:",
    borrowers_clean["borrower_id"].duplicated().sum()
)

Rows after exact deduplication: 30000
Duplicate borrower IDs remaining: 18985


In [161]:
print(borrowers_clean.columns.tolist())

['borrower_id', 'name', 'phone', 'email', 'city', 'created_at', 'updated_at', 'state']


In [162]:
print(
    borrowers_clean.groupby("borrower_id").size().describe()
)

count    11015.000000
mean         2.723559
std          1.468983
min          1.000000
25%          2.000000
50%          2.000000
75%          4.000000
max         11.000000
dtype: float64


In [163]:
for col in ["name", "phone", "email", "city", "created_at", "updated_at", "state"]:
    print(
        col,
        "->",
        borrowers_clean.groupby("borrower_id")[col].nunique().mean()
    )

name -> 2.405265546981389
phone -> 2.6687244666364047
email -> 2.6435769405356333
city -> 2.4025419881979118
created_at -> 2.7235587834770767
updated_at -> 2.7235587834770767
state -> 2.349341806627326


In [164]:
print(
    borrowers_clean[
        borrowers_clean["borrower_id"] == 
        borrowers_clean["borrower_id"].value_counts().index[0]
    ]
)


      borrower_id          name         phone                  email  \
1280   BRW0008879   Priya Mehta  9.845814e+09  user18232@example.com   
3194   BRW0008879    Pooja Nair  9.461372e+09  user19616@example.com   
10580  BRW0008879    Neha Singh  9.506041e+09  user12411@example.com   
10600  BRW0008879    Neha Singh  9.146559e+09                    NaN   
13433  BRW0008879   Rahul Verma  9.203332e+09  user12489@example.com   
13827  BRW0008879   Vikram Shah  9.855081e+09  user17960@example.com   
15176  BRW0008879  Aarav Sharma  9.585574e+09  user16090@example.com   
16706  BRW0008879   Priya Mehta  9.064240e+09  user19316@example.com   
20752  BRW0008879    Neha Singh  9.494792e+09   user4825@example.com   
22477  BRW0008879    Neha Singh  9.829333e+09  user17018@example.com   
26134  BRW0008879    Amit Kumar  9.136498e+09   user2417@example.com   

            city           created_at           updated_at        state  
1280   Bengaluru  2026-04-21 18:56:59  2026-04-18 12:09:43   

In [165]:
for col in ["name", "phone", "email", "city", "state"]:
    count = (
        borrowers_clean.groupby("borrower_id")[col]
        .nunique()
        .gt(1)
        .sum()
    )
    print(f"{col}: {count}")

name: 8185
phone: 8399
email: 8334
city: 8159
state: 8070


In [166]:
print(
    "Borrower IDs with multiple records:",
    borrowers_clean["borrower_id"].duplicated().groupby(
        borrowers_clean["borrower_id"]
    ).any().sum()
)


Borrower IDs with multiple records: 8518


### Finding: Borrower Identity Corruption

After removing 600 exact duplicate rows, 30,000 borrower records remain.

8,518 borrower IDs have multiple records. These records frequently
contain conflicting identity attributes:

Name: 8,185
Phone: 8,399
Email: 8,334
City: 8,159
State: 8,070

Therefore, borrower_id cannot be treated as a reliable unique borrower
key. The Golden Dataset should preserve these records and flag the
identity conflicts rather than arbitrarily selecting one record.

In [167]:
borrower_conflict_ids = (
    borrowers_clean.groupby("borrower_id")
    .agg(
        name_n=("name", "nunique"),
        phone_n=("phone", "nunique"),
        email_n=("email", "nunique"),
        city_n=("city", "nunique"),
        state_n=("state", "nunique")
    )
)

borrower_conflict_ids["identity_conflict"] = (
    borrower_conflict_ids[
        ["name_n", "phone_n", "email_n", "city_n", "state_n"]
    ].max(axis=1) > 1
)

print(
    "Borrower IDs with identity conflicts:",
    borrower_conflict_ids["identity_conflict"].sum()
)

Borrower IDs with identity conflicts: 8518


In [168]:
borrowers_clean = borrowers_clean.merge(
    borrower_conflict_ids["identity_conflict"],
    on="borrower_id",
    how="left"
)

borrowers_clean["identity_conflict"] = (
    borrowers_clean["identity_conflict"]
    .fillna(False)
)

In [169]:
print(
    borrowers_clean["identity_conflict"].value_counts()
)

identity_conflict
True     27503
False     2497
Name: count, dtype: int64


### Borrower Cleaning Result

After removing exact duplicates, 30,000 borrower records remain.

27,503 records belong to borrower IDs with identity conflicts.
2,497 records have no detected identity conflict.

Because the conflicts affect multiple identity attributes, conflicted
records are retained and flagged rather than arbitrarily deduplicated.

In [170]:
borrowers_clean.to_csv(
    "../data/processed/borrowers_clean.csv",
    index=False
)

print("Saved borrowers_clean.csv")

Saved borrowers_clean.csv


In [171]:
import os

print(
    "File exists:",
    os.path.exists("../data/processed/borrowers_clean.csv")
)

File exists: True


## 3; Accounts table

In [172]:
accounts = datasets["accounts"].copy()

print("Original rows:", len(accounts))
print("Exact duplicate rows:", accounts.duplicated().sum())
print("Duplicate account IDs:", accounts["account_id"].duplicated().sum())

Original rows: 30000
Exact duplicate rows: 0
Duplicate account IDs: 0


In [173]:
print(accounts.isna().sum())

account_id              0
borrower_id           455
loan_type               0
principal_amount        0
outstanding_amount      0
dpd                     0
risk_segment            0
status                  0
opened_at               0
timezone                0
schema_version          0
dtype: int64


In [174]:
print(accounts.dtypes)

account_id             object
borrower_id            object
loan_type              object
principal_amount      float64
outstanding_amount    float64
dpd                     int64
risk_segment           object
status                 object
opened_at              object
timezone               object
schema_version         object
dtype: object


In [175]:
accounts_clean = accounts.copy()

accounts_clean["opened_at"] = pd.to_datetime(
    accounts_clean["opened_at"],
    errors="coerce"
)

print(
    "Invalid opened_at:",
    accounts_clean["opened_at"].isna().sum()
)

Invalid opened_at: 0


In [176]:
print(accounts_clean[
    ["principal_amount", "outstanding_amount", "dpd"]
].describe())

       principal_amount  outstanding_amount           dpd
count      30000.000000        30000.000000  30000.000000
mean      403455.521785       349634.511433     56.506433
std       228521.364422       201660.392809     53.970460
min        10055.110000         1002.670000      0.000000
25%       204114.102500       175556.815000      5.000000
50%       403456.505000       349587.085000     45.000000
75%       601484.350000       522953.687500     90.000000
max       799968.380000       699963.890000    180.000000


In [177]:
print(
    "Outstanding > Principal:",
    (accounts_clean["outstanding_amount"] >
     accounts_clean["principal_amount"]).sum()
)

print(
    "Negative DPD:",
    (accounts_clean["dpd"] < 0).sum()
)

print(
    "Negative principal:",
    (accounts_clean["principal_amount"] < 0).sum()
)

print(
    "Negative outstanding:",
    (accounts_clean["outstanding_amount"] < 0).sum()
)

Outstanding > Principal: 13029
Negative DPD: 0
Negative principal: 0
Negative outstanding: 0


In [178]:
for col in ["loan_type", "risk_segment", "status"]:
    print("\n", col)
    print(accounts_clean[col].value_counts())


 loan_type
loan_type
CREDIT_CARD    6080
AUTO           6079
PERSONAL       5983
CONSUMER       5930
BNPL           5928
Name: count, dtype: int64

 risk_segment
risk_segment
HIGH      7552
MEDIUM    7533
LOW       7513
NPA       7402
Name: count, dtype: int64

 status
status
ACTIVE      7539
CLOSED      7496
PAID        7486
WRITEOFF    7479
Name: count, dtype: int64


### Finding: Outstanding Amount Anomaly

13,029 of 30,000 accounts have outstanding_amount greater than
principal_amount.

No negative principal, outstanding amount, or DPD values were found.

The outstanding_amount anomaly is retained and flagged rather than
automatically corrected because the business definition of these
financial fields is not available.

In [179]:
accounts_clean["outstanding_gt_principal"] = (
    accounts_clean["outstanding_amount"] >
    accounts_clean["principal_amount"]
)

print(
    accounts_clean["outstanding_gt_principal"].value_counts()
)

outstanding_gt_principal
False    16971
True     13029
Name: count, dtype: int64


In [180]:
accounts_clean.to_csv(
    "../data/processed/accounts_clean.csv",
    index=False
)

print("Saved accounts_clean.csv")

Saved accounts_clean.csv


In [181]:
import os

print(
    "File exists:",
    os.path.exists("../data/processed/accounts_clean.csv")
)

File exists: True


## 4. Calls table

In [182]:
calls = datasets["calls"].copy()

print("Original rows:", len(calls))
print("Exact duplicate rows:", calls.duplicated().sum())
print("Duplicate call IDs:", calls["call_id"].duplicated().sum())

Original rows: 91350
Exact duplicate rows: 1271
Duplicate call IDs: 1350


In [183]:
call_id_counts = calls["call_id"].value_counts()

print(
    "Call IDs appearing more than once:",
    (call_id_counts > 1).sum()
)

print(
    call_id_counts[call_id_counts > 1].head(10)
)

Call IDs appearing more than once: 1350
call_id
CALL0012944    2
CALL0034936    2
CALL0034934    2
CALL0031598    2
CALL0010728    2
CALL0054331    2
CALL0055570    2
CALL0077246    2
CALL0077248    2
CALL0049267    2
Name: count, dtype: int64


In [184]:
duplicate_call_ids = call_id_counts[
    call_id_counts > 1
].index

print(
    calls[calls["call_id"].isin(duplicate_call_ids)]
    .sort_values("call_id")
    .head(20)
)

           call_id  account_id borrower_id             event_at    agent_id  \
49     CALL0000050  ACC0025237  BRW0005568  2026-04-24 23:15:21  AGT0000269   
90547  CALL0000050  ACC0025237  BRW0005568  2026-04-24 23:15:21  AGT0000269   
77     CALL0000078  ACC0022457  BRW0003774  2026-06-03 18:45:40  AGT0000559   
91339  CALL0000078  ACC0022457  BRW0003774  2026-06-03 18:45:40  AGT0000559   
96     CALL0000097  ACC0022138  BRW0003543  2026-01-26 15:40:38  AGT0000194   
90330  CALL0000097  ACC0022138  BRW0003543  2026-01-26 15:40:38  AGT0000194   
200    CALL0000201  ACC0012733  BRW0007105  2026-01-27 09:39:40  AGT0000584   
90685  CALL0000201  ACC0012733  BRW0007105  2026-01-27 09:39:40  AGT0000584   
225    CALL0000226  ACC0010288  BRW0011653  2026-01-09 11:36:06  AGT0000584   
90485  CALL0000226  ACC0010288  BRW0011653  2026-01-12 11:36:06  AGT0000584   
284    CALL0000285  ACC0023905  BRW0008006  2026-01-02 09:58:17  AGT0000845   
90880  CALL0000285  ACC0023905  BRW0008006  2026-01-

In [185]:
duplicate_calls = calls[
    calls["call_id"].duplicated(keep=False)
].copy()

duplicate_calls["row_signature"] = (
    duplicate_calls.drop(columns=["call_id"])
    .astype(str)
    .agg("|".join, axis=1)
)

signature_counts = (
    duplicate_calls.groupby("call_id")["row_signature"]
    .nunique()
)

print("Duplicate call IDs:", len(signature_counts))
print(
    "Exact duplicate call IDs:",
    (signature_counts == 1).sum()
)
print(
    "Conflicting duplicate call IDs:",
    (signature_counts > 1).sum()
)

Duplicate call IDs: 1350
Exact duplicate call IDs: 1271
Conflicting duplicate call IDs: 79


In [186]:
calls_clean = calls.drop_duplicates().copy()

print("Original rows:", len(calls))
print("After exact deduplication:", len(calls_clean))
print("Rows removed:", len(calls) - len(calls_clean))

Original rows: 91350
After exact deduplication: 90079
Rows removed: 1271


In [187]:
print(
    "Remaining duplicate call IDs:",
    calls_clean["call_id"].duplicated().sum()
)

Remaining duplicate call IDs: 79


In [188]:
conflicting_call_ids = signature_counts[
    signature_counts > 1
].index

calls_clean["call_id_conflict"] = (
    calls_clean["call_id"].isin(conflicting_call_ids)
)

print(calls_clean["call_id_conflict"].value_counts())

call_id_conflict
False    89921
True       158
Name: count, dtype: int64


In [189]:
print(
    "Missing agent_id:",
    calls_clean["agent_id"].isna().sum()
)

Missing agent_id: 1827


In [190]:
calls_clean["agent_id_missing"] = (
    calls_clean["agent_id"].isna()
)

print(calls_clean["agent_id_missing"].value_counts())

agent_id_missing
False    88252
True      1827
Name: count, dtype: int64


In [191]:
calls_clean["event_at"] = pd.to_datetime(
    calls_clean["event_at"],
    errors="coerce"
)

print(
    "Invalid event_at:",
    calls_clean["event_at"].isna().sum()
)

Invalid event_at: 0


In [192]:
print("Negative duration:",
      (calls_clean["duration_sec"] < 0).sum())

print("Zero duration:",
      (calls_clean["duration_sec"] == 0).sum())

print(calls_clean["duration_sec"].describe())

Negative duration: 0
Zero duration: 99
count    90079.000000
mean       451.030640
std        259.018362
min          0.000000
25%        228.000000
50%        451.000000
75%        676.000000
max        899.000000
Name: duration_sec, dtype: float64


### Finding: Call Duration

No negative call durations were found. 99 calls have zero duration.
Zero-duration calls are retained because they may be valid for
non-connected call outcomes.

In [193]:
print(calls_clean["call_status"].value_counts())

call_status
NO_ANSWER    18092
BUSY         18078
FAILED       18014
VOICEMAIL    17999
ANSWERED     17896
Name: count, dtype: int64


In [194]:
print(
    calls_clean.groupby("call_status")["duration_sec"]
    .agg(["count", "mean", "min", "max"])
)

             count        mean  min  max
call_status                             
ANSWERED     17896  452.947251    0  899
BUSY         18078  450.685529    0  899
FAILED       18014  450.918952    0  899
NO_ANSWER    18092  448.541289    0  899
VOICEMAIL    17999  452.085616    0  899


In [195]:
calls_clean.to_csv(
    "../data/processed/calls_clean.csv",
    index=False
)

print("Saved calls_clean.csv")

Saved calls_clean.csv


In [196]:
import os

print(
    "File exists:",
    os.path.exists("../data/processed/calls_clean.csv")
)

File exists: True


## 5. call_attempts

In [197]:
call_attempts = datasets["call_attempts"].copy()

print("Original rows:", len(call_attempts))
print("Exact duplicate rows:", call_attempts.duplicated().sum())
print("Duplicate attempt IDs:",
      call_attempts["attempt_id"].duplicated().sum())

Original rows: 120000
Exact duplicate rows: 0
Duplicate attempt IDs: 0


In [198]:
print(call_attempts.isna().sum())

attempt_id           0
account_id           0
borrower_id          0
event_at             0
call_id              0
agent_id             0
attempt_no           0
vendor_id         2400
attempt_status       0
dtype: int64


In [199]:
print(call_attempts.dtypes)

attempt_id        object
account_id        object
borrower_id       object
event_at          object
call_id           object
agent_id          object
attempt_no         int64
vendor_id         object
attempt_status    object
dtype: object


In [200]:
call_attempts_clean = call_attempts.copy()

call_attempts_clean["event_at"] = pd.to_datetime(
    call_attempts_clean["event_at"],
    errors="coerce"
)

print(
    "Invalid event_at:",
    call_attempts_clean["event_at"].isna().sum()
)

Invalid event_at: 0


In [201]:
print(
    call_attempts_clean["attempt_no"].describe()
)

print(
    "Invalid attempt_no:",
    (call_attempts_clean["attempt_no"] <= 0).sum()
)

count    120000.000000
mean          4.002458
std           1.999951
min           1.000000
25%           2.000000
50%           4.000000
75%           6.000000
max           7.000000
Name: attempt_no, dtype: float64
Invalid attempt_no: 0


### Finding: Call Attempt Data

120,000 call attempts have unique attempt_id values and no exact
duplicates.

event_at contains no invalid dates.

attempt_no ranges from 1 to 7, with no zero or negative values.

2,400 records have missing vendor_id and should be retained and flagged.

In [202]:
call_attempts_clean["vendor_id_missing"] = (
    call_attempts_clean["vendor_id"].isna()
)

print(
    call_attempts_clean["vendor_id_missing"].value_counts()
)

vendor_id_missing
False    117600
True       2400
Name: count, dtype: int64


In [203]:
call_attempts_clean.to_csv(
    "../data/processed/call_attempts_clean.csv",
    index=False
)

print("Saved call_attempts_clean.csv")

Saved call_attempts_clean.csv


## 6. promises_to_pay table

In [204]:
ptp = datasets["promises_to_pay"].copy()

print("Original rows:", len(ptp))
print("Exact duplicate rows:", ptp.duplicated().sum())
print("Duplicate ptp IDs:", ptp["ptp_id"].duplicated().sum())

Original rows: 18000
Exact duplicate rows: 0
Duplicate ptp IDs: 0


In [205]:
print(ptp.isna().sum())

ptp_id             0
account_id         0
borrower_id        0
event_at           0
agent_id           0
promised_amount    0
promised_date      0
status             0
source             0
dtype: int64


In [206]:
print(ptp.dtypes)

ptp_id              object
account_id          object
borrower_id         object
event_at            object
agent_id            object
promised_amount    float64
promised_date       object
status              object
source              object
dtype: object


In [207]:
ptp_clean = ptp.copy()

ptp_clean["event_at"] = pd.to_datetime(
    ptp_clean["event_at"],
    errors="coerce"
)

ptp_clean["promised_date"] = pd.to_datetime(
    ptp_clean["promised_date"],
    errors="coerce"
)

print("Invalid event_at:", ptp_clean["event_at"].isna().sum())
print("Invalid promised_date:", ptp_clean["promised_date"].isna().sum())

Invalid event_at: 0
Invalid promised_date: 0


In [208]:
print(ptp_clean["promised_amount"].describe())

print(
    "Negative promised amounts:",
    (ptp_clean["promised_amount"] < 0).sum()
)

count    18000.000000
mean     50233.838778
std      28631.753710
min        511.990000
25%      25441.330000
50%      50312.005000
75%      74975.027500
max      99997.280000
Name: promised_amount, dtype: float64
Negative promised amounts: 0


### PTP Data Quality

18,000 PTP records have unique ptp_id values and no missing fields.

event_at and promised_date contain no invalid dates.

promised_amount contains no negative values and ranges from
₹511.99 to ₹99,997.28.

In [209]:
invalid_ptp_dates = (
    ptp_clean["promised_date"].dt.normalize()
    < ptp_clean["event_at"].dt.normalize()
)

print(
    "Promised date before PTP event:",
    invalid_ptp_dates.sum()
)

Promised date before PTP event: 0


In [210]:
print(ptp_clean["status"].value_counts())

status
BROKEN       4553
CANCELLED    4543
KEPT         4489
OPEN         4415
Name: count, dtype: int64


In [211]:
ptp_clean.to_csv(
    "../data/processed/promises_to_pay_clean.csv",
    index=False
)

print("Saved promises_to_pay_clean.csv")

Saved promises_to_pay_clean.csv


In [212]:
import os

print(
    os.path.exists(
        "../data/processed/promises_to_pay_clean.csv"
    )
)

True


## 7 .daily_targeting

In [214]:
daily_targeting = datasets["daily_targeting"].copy()

print("Original rows:", len(daily_targeting))
print("Exact duplicate rows:", daily_targeting.duplicated().sum())
print(
    "Duplicate target IDs:",
    daily_targeting["target_id"].duplicated().sum()
)

Original rows: 45000
Exact duplicate rows: 0
Duplicate target IDs: 0


In [215]:
print(daily_targeting.isna().sum())

target_id              0
account_id             0
campaign_id            0
target_date            0
priority               0
recommended_channel    0
status                 0
dtype: int64


In [216]:
print(daily_targeting.dtypes)

target_id              object
account_id             object
campaign_id            object
target_date            object
priority                int64
recommended_channel    object
status                 object
dtype: object


In [217]:
targeting_clean = daily_targeting.copy()

targeting_clean["target_date"] = pd.to_datetime(
    targeting_clean["target_date"],
    errors="coerce"
)

print(
    "Invalid target_date:",
    targeting_clean["target_date"].isna().sum()
)

print(
    "Targeting start:",
    targeting_clean["target_date"].min()
)

print(
    "Targeting end:",
    targeting_clean["target_date"].max()
)

Invalid target_date: 0
Targeting start: 2026-01-01 00:00:00
Targeting end: 2026-08-08 00:00:00


In [218]:
print(targeting_clean["priority"].describe())

print(
    "Invalid priority:",
    (targeting_clean["priority"] <= 0).sum()
)

count    45000.000000
mean         5.505600
std          2.877085
min          1.000000
25%          3.000000
50%          6.000000
75%          8.000000
max         10.000000
Name: priority, dtype: float64
Invalid priority: 0


### Daily Targeting Data Quality

45,000 targeting records have unique target_id values and no missing
fields.

target_date contains no invalid dates and ranges from Jan 1, 2026
to Aug 8, 2026.

Priority values range from 1 to 10 with no invalid values.

In [219]:
print(targeting_clean["recommended_channel"].value_counts())

recommended_channel
FIELD       11365
SMS         11221
WHATSAPP    11212
VOICE       11202
Name: count, dtype: int64


In [220]:
print(targeting_clean["status"].value_counts())

status
EXPIRED      11371
CONTACTED    11254
QUEUED       11202
SKIPPED      11173
Name: count, dtype: int64


In [221]:
print(targeting_clean["priority"].value_counts().sort_index())

priority
1     4531
2     4539
3     4520
4     4358
5     4401
6     4432
7     4641
8     4587
9     4539
10    4452
Name: count, dtype: int64


### Daily Targeting Data Quality

45,000 targeting records have valid unique target_id values and no
missing fields.

There are four recommended channels: FIELD, SMS, WHATSAPP, and VOICE.

Statuses are distributed across EXPIRED, CONTACTED, QUEUED, and SKIPPED.

Priority values range from 1 to 10, with no invalid priority values.

In [222]:
targeting_clean.to_csv(
    "../data/processed/daily_targeting_clean.csv",
    index=False
)

print("Saved daily_targeting_clean.csv")

Saved daily_targeting_clean.csv


In [223]:
import os

print(
    os.path.exists(
        "../data/processed/daily_targeting_clean.csv"
    )
)

True


## 8 . campaigns

In [224]:
campaigns = datasets["campaigns"].copy()

print("Original rows:", len(campaigns))
print("Exact duplicate rows:", campaigns.duplicated().sum())
print(
    "Duplicate campaign IDs:",
    campaigns["campaign_id"].duplicated().sum()
)

Original rows: 120
Exact duplicate rows: 0
Duplicate campaign IDs: 0


In [225]:
print(campaigns.isna().sum())

campaign_id          0
campaign_name        0
channel              0
strategy_version     0
start_at             0
target_definition    0
end_at               0
dtype: int64


In [226]:
print(campaigns.dtypes)

campaign_id          object
campaign_name        object
channel              object
strategy_version     object
start_at             object
target_definition    object
end_at               object
dtype: object


In [227]:
campaigns_clean = campaigns.copy()

campaigns_clean["start_at"] = pd.to_datetime(
    campaigns_clean["start_at"],
    errors="coerce"
)

campaigns_clean["end_at"] = pd.to_datetime(
    campaigns_clean["end_at"],
    errors="coerce"
)

print("Invalid start_at:", campaigns_clean["start_at"].isna().sum())
print("Invalid end_at:", campaigns_clean["end_at"].isna().sum())

print(
    "End before start:",
    (
        campaigns_clean["end_at"] <
        campaigns_clean["start_at"]
    ).sum()
)

Invalid start_at: 0
Invalid end_at: 0
End before start: 0


In [228]:
print(campaigns_clean["channel"].value_counts())

channel
WHATSAPP    31
SMS         28
MIXED       23
VOICE       20
FIELD       18
Name: count, dtype: int64


In [229]:
print(campaigns_clean["strategy_version"].value_counts())

strategy_version
legacy    37
v3        32
v2        27
v1        24
Name: count, dtype: int64


In [230]:
campaigns_clean.to_csv(
    "../data/processed/campaigns_clean.csv",
    index=False
)

print("Saved campaigns_clean.csv")

Saved campaigns_clean.csv


In [231]:
import os

print(
    os.path.exists(
        "../data/processed/campaigns_clean.csv"
    )
)

True


## 9.field_visits table

In [232]:
field_visits = datasets["field_visits"].copy()

print("Original rows:", len(field_visits))
print("Exact duplicate rows:", field_visits.duplicated().sum())
print(
    "Duplicate visit IDs:",
    field_visits["visit_id"].duplicated().sum()
)


Original rows: 25000
Exact duplicate rows: 0
Duplicate visit IDs: 0


In [233]:
print(field_visits.isna().sum())

visit_id          0
account_id        0
borrower_id       0
event_at          0
agent_id          0
visit_type        0
outcome           0
latitude          0
longitude         0
scheduled_at    250
dtype: int64


In [234]:
print(field_visits.dtypes)

visit_id         object
account_id       object
borrower_id      object
event_at         object
agent_id         object
visit_type       object
outcome          object
latitude        float64
longitude       float64
scheduled_at     object
dtype: object


In [235]:
field_visits_clean = field_visits.copy()

field_visits_clean["event_at"] = pd.to_datetime(
    field_visits_clean["event_at"],
    errors="coerce"
)

field_visits_clean["scheduled_at"] = pd.to_datetime(
    field_visits_clean["scheduled_at"],
    errors="coerce"
)

print("Invalid event_at:",
      field_visits_clean["event_at"].isna().sum())

print("Invalid scheduled_at:",
      field_visits_clean["scheduled_at"].isna().sum())

print(
    "Invalid latitude:",
    ((field_visits_clean["latitude"] < -90) |
     (field_visits_clean["latitude"] > 90)).sum()
)

print(
    "Invalid longitude:",
    ((field_visits_clean["longitude"] < -180) |
     (field_visits_clean["longitude"] > 180)).sum()
)

Invalid event_at: 0
Invalid scheduled_at: 250
Invalid latitude: 0
Invalid longitude: 0


### Field Visits Data Quality

25,000 field visit records have unique visit_id values and no exact
duplicates.

event_at contains no invalid dates.

250 records have missing scheduled_at values.

Latitude and longitude values are all within valid geographic ranges.

In [236]:
print(field_visits_clean["visit_type"].value_counts())

visit_type
FIRST_VISIT    6275
FOLLOWUP       6271
NOTICE         6262
AFTER_HOURS    6192
Name: count, dtype: int64


In [237]:
print(field_visits_clean["outcome"].value_counts())

outcome
WRONG_ADDRESS    4221
CONTACTED        4205
PTP              4200
NOT_AVAILABLE    4190
REFUSED          4104
PAID             4080
Name: count, dtype: int64


# Field Visits Data Quality

25,000 field visit records have unique visit_id values and no exact
duplicates.

visit_type contains four categories and outcome contains six categories.

250 records have missing scheduled_at values. These records are retained
without imputing the missing schedule.m

In [238]:
field_visits_clean.to_csv(
    "../data/processed/field_visits_clean.csv",
    index=False
)

print("Saved field_visits_clean.csv")

Saved field_visits_clean.csv


In [239]:
import os

print(
    os.path.exists(
        "../data/processed/field_visits_clean.csv"
    )
)

True


## 9.complaints table

In [240]:
complaints = datasets["complaints"].copy()

print("Original rows:", len(complaints))
print("Exact duplicate rows:", complaints.duplicated().sum())
print(
    "Duplicate complaint IDs:",
    complaints["complaint_id"].duplicated().sum()
)

Original rows: 8000
Exact duplicate rows: 0
Duplicate complaint IDs: 0


In [241]:
print(complaints.isna().sum())

complaint_id      0
account_id        0
borrower_id       0
event_at          0
complaint_type    0
severity          0
status            0
source            0
resolution_at     0
dtype: int64


In [242]:
print(complaints.dtypes)

complaint_id      object
account_id        object
borrower_id       object
event_at          object
complaint_type    object
severity          object
status            object
source            object
resolution_at     object
dtype: object


In [243]:
complaints_clean = complaints.copy()

complaints_clean["event_at"] = pd.to_datetime(
    complaints_clean["event_at"],
    errors="coerce"
)

complaints_clean["resolution_at"] = pd.to_datetime(
    complaints_clean["resolution_at"],
    errors="coerce"
)

print("Invalid event_at:",
      complaints_clean["event_at"].isna().sum())

print("Invalid resolution_at:",
      complaints_clean["resolution_at"].isna().sum())

Invalid event_at: 0
Invalid resolution_at: 0


In [244]:
print(
    "Resolution before complaint:",
    (
        complaints_clean["resolution_at"]
        < complaints_clean["event_at"]
    ).sum()
)

Resolution before complaint: 0


In [245]:
print(complaints_clean["complaint_type"].value_counts())

complaint_type
AGENT_BEHAVIOUR    1202
PRIVACY            1155
DISPUTE            1155
DND                1152
HARASSMENT         1126
PAYMENT            1112
WRONG_CONTACT      1098
Name: count, dtype: int64


In [246]:
print(complaints_clean["severity"].value_counts())

severity
MEDIUM      2047
HIGH        1997
LOW         1988
CRITICAL    1968
Name: count, dtype: int64


In [247]:
print(complaints_clean["status"].value_counts())

status
OPEN             2096
INVESTIGATING    2005
CLOSED           1964
RESOLVED         1935
Name: count, dtype: int64


### Complaints Data Quality

8,000 complaint records have unique complaint_id values and no
missing fields.

event_at and resolution_at contain valid dates, with no resolution
occurring before the complaint.

Complaint types, severity levels, and statuses contain valid
categorical values.

In [248]:
complaints_clean.to_csv(
    "../data/processed/complaints_clean.csv",
    index=False
)

print("Saved complaints_clean.csv")

Saved complaints_clean.csv


In [249]:
import os

print(
    os.path.exists(
        "../data/processed/complaints_clean.csv"
    )
)

True


## 11 : whatsapp_events table

In [251]:
whatsapp_events = datasets["whatsapp_events"].copy()

print("Original rows:", len(whatsapp_events))
print("Exact duplicate rows:", whatsapp_events.duplicated().sum())
print(
    "Duplicate whatsapp_event_id:",
    whatsapp_events["whatsapp_event_id"].duplicated().sum()
)

Original rows: 60600
Exact duplicate rows: 600
Duplicate whatsapp_event_id: 600


In [252]:
whatsapp_clean = whatsapp_events.drop_duplicates().copy()

print("Original rows:", len(whatsapp_events))
print("Clean rows:", len(whatsapp_clean))
print("Rows removed:", len(whatsapp_events) - len(whatsapp_clean))

Original rows: 60600
Clean rows: 60000
Rows removed: 600


In [253]:
print(
    "Remaining duplicate IDs:",
    whatsapp_clean["whatsapp_event_id"].duplicated().sum()
)

Remaining duplicate IDs: 0


In [254]:
print(whatsapp_clean.isna().sum())

whatsapp_event_id    0
account_id           0
borrower_id          0
event_at             0
message_id           0
event_type           0
template_code        0
provider_id          0
dtype: int64


In [255]:
print(whatsapp_clean.dtypes)

whatsapp_event_id    object
account_id           object
borrower_id          object
event_at             object
message_id           object
event_type           object
template_code        object
provider_id          object
dtype: object


In [256]:
whatsapp_clean["event_at"] = pd.to_datetime(
    whatsapp_clean["event_at"],
    errors="coerce"
)

print(
    "Invalid event_at:",
    whatsapp_clean["event_at"].isna().sum()
)

Invalid event_at: 0


In [257]:
print(
    whatsapp_clean["event_type"].value_counts()
)

event_type
SENT             10145
PAYMENT_CLICK    10056
FAILED           10029
REPLIED           9935
READ              9928
DELIVERED         9907
Name: count, dtype: int64


In [258]:
whatsapp_clean.to_csv(
    "../data/processed/whatsapp_events_clean.csv",
    index=False
)

print("Saved whatsapp_events_clean.csv")

Saved whatsapp_events_clean.csv


In [259]:
import os

print(
    os.path.exists(
        "../data/processed/whatsapp_events_clean.csv"
    )
)

True


## 12:sms_events table

In [260]:
sms_events = datasets["sms_events"].copy()

print("Original rows:", len(sms_events))
print("Exact duplicate rows:", sms_events.duplicated().sum())
print(
    "Duplicate sms_event_id:",
    sms_events["sms_event_id"].duplicated().sum()
)

Original rows: 45000
Exact duplicate rows: 0
Duplicate sms_event_id: 0


In [261]:
print(sms_events.isna().sum())

sms_event_id     0
account_id       0
borrower_id      0
event_at         0
message_id       0
event_type       0
template_code    0
provider_id      0
dtype: int64


In [262]:
print(sms_events.dtypes)

sms_event_id     object
account_id       object
borrower_id      object
event_at         object
message_id       object
event_type       object
template_code    object
provider_id      object
dtype: object


In [263]:
sms_clean = sms_events.copy()

sms_clean["event_at"] = pd.to_datetime(
    sms_clean["event_at"],
    errors="coerce"
)

print(
    "Invalid event_at:",
    sms_clean["event_at"].isna().sum()
)

Invalid event_at: 0


In [264]:
print(
    sms_clean["event_type"].value_counts()
)

event_type
SENT         11391
FAILED       11251
DELIVERED    11219
CLICKED      11139
Name: count, dtype: int64


In [265]:
sms_clean = sms_events.copy()

sms_clean["event_at"] = pd.to_datetime(
    sms_clean["event_at"],
    errors="coerce"
)

print(
    "Invalid event_at:",
    sms_clean["event_at"].isna().sum()
)

Invalid event_at: 0


In [266]:
print(
    sms_clean["event_type"].value_counts()
)

event_type
SENT         11391
FAILED       11251
DELIVERED    11219
CLICKED      11139
Name: count, dtype: int64


In [267]:
sms_clean.to_csv(
    "../data/processed/sms_events_clean.csv",
    index=False
)

print("Saved sms_events_clean.csv")

Saved sms_events_clean.csv


In [268]:
import os

print(
    os.path.exists(
        "../data/processed/sms_events_clean.csv"
    )
)

True


## 13 : account_status_history table

In [269]:
account_status_history = datasets["account_status_history"].copy()

print("Original rows:", len(account_status_history))
print(
    "Exact duplicate rows:",
    account_status_history.duplicated().sum()
)
print(
    "Duplicate history IDs:",
    account_status_history["history_id"].duplicated().sum()
)

Original rows: 60000
Exact duplicate rows: 0
Duplicate history IDs: 0


In [270]:
print(account_status_history.isna().sum())

history_id     0
account_id     0
borrower_id    0
event_at       0
status         0
changed_by     0
source         0
recorded_at    0
dtype: int64


In [271]:
print(account_status_history.dtypes)

history_id     object
account_id     object
borrower_id    object
event_at       object
status         object
changed_by     object
source         object
recorded_at    object
dtype: object


In [272]:
history_clean = account_status_history.copy()

history_clean["event_at"] = pd.to_datetime(
    history_clean["event_at"],
    errors="coerce"
)

history_clean["recorded_at"] = pd.to_datetime(
    history_clean["recorded_at"],
    errors="coerce"
)

print("Invalid event_at:",
      history_clean["event_at"].isna().sum())

print("Invalid recorded_at:",
      history_clean["recorded_at"].isna().sum())

Invalid event_at: 0
Invalid recorded_at: 0


In [273]:
print(
    "Recorded before event:",
    (
        history_clean["recorded_at"]
        < history_clean["event_at"]
    ).sum()
)

Recorded before event: 30191


### Finding: Account Status Timestamp Anomaly

30,191 account status history records have recorded_at earlier than
event_at.

The original timestamps are retained and the records are flagged rather
than automatically corrected.

In [274]:
history_clean["recorded_before_event"] = (
    history_clean["recorded_at"] <
    history_clean["event_at"]
)

print(
    history_clean["recorded_before_event"].value_counts()
)

recorded_before_event
True     30191
False    29809
Name: count, dtype: int64


In [275]:
print(history_clean["status"].value_counts())

status
PAID          8650
CLOSED        8614
DELINQUENT    8612
NPA           8612
WRITEOFF      8583
ACTIVE        8518
PTP           8411
Name: count, dtype: int64


In [276]:
history_clean.to_csv(
    "../data/processed/account_status_history_clean.csv",
    index=False
)

print("Saved account_status_history_clean.csv")

Saved account_status_history_clean.csv


In [277]:
import os

print(
    os.path.exists(
        "../data/processed/account_status_history_clean.csv"
    )
)

True


## 14. agent_sessions table 

In [278]:
agent_sessions = datasets["agent_sessions"].copy()

print("Original rows:", len(agent_sessions))
print("Exact duplicate rows:", agent_sessions.duplicated().sum())
print(
    "Duplicate session IDs:",
    agent_sessions["session_id"].duplicated().sum()
)

Original rows: 15000
Exact duplicate rows: 0
Duplicate session IDs: 0


In [279]:
print(agent_sessions.isna().sum())

session_id    0
agent_id      0
login_at      0
channel       0
device_id     0
timezone      0
logout_at     0
dtype: int64


In [280]:
print(agent_sessions.dtypes)

session_id    object
agent_id      object
login_at      object
channel       object
device_id     object
timezone      object
logout_at     object
dtype: object


In [281]:
sessions_clean = agent_sessions.copy()

sessions_clean["login_at"] = pd.to_datetime(
    sessions_clean["login_at"],
    errors="coerce"
)

sessions_clean["logout_at"] = pd.to_datetime(
    sessions_clean["logout_at"],
    errors="coerce"
)

print("Invalid login_at:",
      sessions_clean["login_at"].isna().sum())

print("Invalid logout_at:",
      sessions_clean["logout_at"].isna().sum())

print(
    "Logout before login:",
    (
        sessions_clean["logout_at"] <
        sessions_clean["login_at"]
    ).sum()
)

Invalid login_at: 0
Invalid logout_at: 0
Logout before login: 0


In [282]:
session_duration = (
    sessions_clean["logout_at"] -
    sessions_clean["login_at"]
).dt.total_seconds()

print(session_duration.describe())

print(
    "Zero-duration sessions:",
    (session_duration == 0).sum()
)

print(
    "Negative-duration sessions:",
    (session_duration < 0).sum()
)

count    15000.000000
mean     18929.013067
std       9862.791080
min       1800.000000
25%      10354.500000
50%      18851.000000
75%      27482.000000
max      35994.000000
dtype: float64
Zero-duration sessions: 0
Negative-duration sessions: 0


In [283]:
print(sessions_clean["channel"].value_counts())

channel
WHATSAPP    3810
FIELD       3796
VOICE       3740
SMS         3654
Name: count, dtype: int64


In [284]:
sessions_clean.to_csv(
    "../data/processed/agent_sessions_clean.csv",
    index=False
)

print("Saved agent_sessions_clean.csv")

Saved agent_sessions_clean.csv


In [285]:
import os

print(
    os.path.exists(
        "../data/processed/agent_sessions_clean.csv"
    )
)

True


## 15 . agents table 

In [286]:
agents = datasets["agents"].copy()

print("Original rows:", len(agents))
print("Exact duplicate rows:", agents.duplicated().sum())
print(
    "Duplicate agent IDs:",
    agents["agent_id"].duplicated().sum()
)

Original rows: 30000
Exact duplicate rows: 0
Duplicate agent IDs: 29000


In [287]:
agent_counts = agents["agent_id"].value_counts()

print(agent_counts.describe())
print()
print(agent_counts.value_counts().sort_index())

count    1000.000000
mean       30.000000
std         5.570011
min        14.000000
25%        26.000000
50%        30.000000
75%        34.000000
max        48.000000
Name: count, dtype: float64

count
14     4
15     1
17     2
18     9
19     7
20    14
21    19
22    29
23    25
24    50
25    58
26    61
27    53
28    75
29    61
30    73
31    62
32    84
33    59
34    56
35    45
36    27
37    37
38    24
39    16
40    18
41     7
42     5
43     6
44     4
45     3
46     2
47     1
48     3
Name: count, dtype: int64


In [288]:
sample_agent = agent_counts.index[0]

print(
    agents[agents["agent_id"] == sample_agent]
)

         agent_id employee_code    agent_name   vendor_id     team     status  \
3236   AGT0000875      EMP00661   Priya Mehta  VND0000001    FIELD   INACTIVE   
3340   AGT0000875      EMP00945   Rohan Patel  VND0000012  DIGITAL  SUSPENDED   
3402   AGT0000875      EMP00007     Sneha Das  VND0000011       T2   INACTIVE   
5091   AGT0000875      EMP00816   Rohan Patel  VND0000001  DIGITAL   INACTIVE   
5314   AGT0000875      EMP00103    Neha Singh  VND0000004  DIGITAL     ACTIVE   
6272   AGT0000875      EMP00615  Aarav Sharma  VND0000008       T3   INACTIVE   
6701   AGT0000875      EMP00352    Neha Singh  VND0000009  DIGITAL     ACTIVE   
6900   AGT0000875      EMP00176   Priya Mehta  VND0000015    FIELD     ACTIVE   
8105   AGT0000875      EMP00570    Ananya Rao  VND0000007       T2   INACTIVE   
9514   AGT0000875      EMP00596     Sneha Das  VND0000014       T2     ACTIVE   
9546   AGT0000875      EMP00113    Ananya Rao  VND0000014       T2   INACTIVE   
10042  AGT0000875      EMP00

In [289]:
agent_identity = (
    agents.groupby("agent_id")
    .agg(
        employee_codes=("employee_code", "nunique"),
        names=("agent_name", "nunique"),
        vendors=("vendor_id", "nunique"),
        teams=("team", "nunique"),
        statuses=("status", "nunique")
    )
)

print("Agents with multiple employee codes:",
      (agent_identity["employee_codes"] > 1).sum())

print("Agents with multiple names:",
      (agent_identity["names"] > 1).sum())

print("Agents with multiple vendors:",
      (agent_identity["vendors"] > 1).sum())

print("Agents with multiple teams:",
      (agent_identity["teams"] > 1).sum())

print("Agents with multiple statuses:",
      (agent_identity["statuses"] > 1).sum())

Agents with multiple employee codes: 1000
Agents with multiple names: 1000
Agents with multiple vendors: 1000
Agents with multiple teams: 1000
Agents with multiple statuses: 1000


In [290]:
agents["joined_at"] = pd.to_datetime(
    agents["joined_at"],
    errors="coerce"
)

agents["updated_at"] = pd.to_datetime(
    agents["updated_at"],
    errors="coerce"
)

print(
    "Invalid joined_at:",
    agents["joined_at"].isna().sum()
)

print(
    "Invalid updated_at:",
    agents["updated_at"].isna().sum()
)

print(
    "joined_at > updated_at:",
    (agents["joined_at"] > agents["updated_at"]).sum()
)

Invalid joined_at: 0
Invalid updated_at: 0
joined_at > updated_at: 4078


In [291]:
agent_conflict_ids = agent_identity[
    (agent_identity["employee_codes"] > 1) |
    (agent_identity["names"] > 1) |
    (agent_identity["vendors"] > 1) |
    (agent_identity["teams"] > 1) |
    (agent_identity["statuses"] > 1)
].index

agents_clean = agents.copy()

agents_clean["identity_conflict"] = (
    agents_clean["agent_id"].isin(agent_conflict_ids)
)

agents_clean["joined_after_updated"] = (
    agents_clean["joined_at"] >
    agents_clean["updated_at"]
)

print(agents_clean["identity_conflict"].value_counts())
print()
print(agents_clean["joined_after_updated"].value_counts())

identity_conflict
True    30000
Name: count, dtype: int64

joined_after_updated
False    25922
True      4078
Name: count, dtype: int64


In [292]:
agents_clean.to_csv(
    "../data/processed/agents_clean.csv",
    index=False
)

print("Saved agents_clean.csv")

Saved agents_clean.csv


In [293]:
import os

print(
    "File exists:",
    os.path.exists("../data/processed/agents_clean.csv")
)

File exists: True


## 16 . vendor_telephony table

In [297]:
vendor_telephony = datasets["vendor_telephony"].copy()

print("Original rows:", len(vendor_telephony))
print(
    "Exact duplicate rows:",
    vendor_telephony.duplicated().sum()
)
print(
    "Duplicate IDs:",
    vendor_telephony["vendor_id"].duplicated().sum()
)

Original rows: 15
Exact duplicate rows: 0
Duplicate IDs: 0


In [298]:
print(vendor_telephony.isna().sum())

vendor_id            0
vendor_name          0
vendor_account_id    0
timezone             0
status               0
schema_version       0
dtype: int64


In [299]:
print(vendor_telephony.dtypes)

vendor_id            object
vendor_name          object
vendor_account_id    object
timezone             object
status               object
schema_version       object
dtype: object


In [300]:
print(vendor_telephony["status"].value_counts())

status
INACTIVE    9
ACTIVE      6
Name: count, dtype: int64


In [301]:
print(vendor_telephony["timezone"].value_counts())

timezone
UTC             8
Asia/Kolkata    7
Name: count, dtype: int64


In [302]:
print(vendor_telephony["schema_version"].value_counts())

schema_version
v1    7
v3    6
v2    2
Name: count, dtype: int64


In [303]:
vendor_telephony_clean = vendor_telephony.copy()

vendor_telephony_clean.to_csv(
    "../data/processed/vendor_telephony_clean.csv",
    index=False
)

print("Saved vendor_telephony_clean.csv")

Saved vendor_telephony_clean.csv


In [304]:
import os

print(
    "File exists:",
    os.path.exists(
        "../data/processed/vendor_telephony_clean.csv"
    )
)

File exists: True


## 17: call_dispositions table

In [305]:
call_dispositions = datasets["call_dispositions"].copy()

print("Original rows:", len(call_dispositions))
print(
    "Exact duplicate rows:",
    call_dispositions.duplicated().sum()
)
print(
    "Duplicate disposition IDs:",
    call_dispositions["disposition_id"].duplicated().sum()
)

Original rows: 35000
Exact duplicate rows: 0
Duplicate disposition IDs: 0


In [306]:
print(call_dispositions.isna().sum())

disposition_id         0
account_id             0
borrower_id            0
event_at               0
call_id                0
agent_id               0
disposition_code       0
disposition_version    0
dtype: int64


In [307]:
print(call_dispositions.dtypes)

disposition_id         object
account_id             object
borrower_id            object
event_at               object
call_id                object
agent_id               object
disposition_code       object
disposition_version    object
dtype: object


In [308]:
dispositions_clean = call_dispositions.copy()

dispositions_clean["event_at"] = pd.to_datetime(
    dispositions_clean["event_at"],
    errors="coerce"
)

print(
    "Invalid event_at:",
    dispositions_clean["event_at"].isna().sum()
)

Invalid event_at: 0


In [309]:
print(
    dispositions_clean["disposition_code"].value_counts()
)

disposition_code
NO_CONTACT        4010
WRONG_NUMBER      3946
PROMISE_TO_PAY    3926
PTP               3904
PTP_BROKEN        3900
CALLBACK          3872
DISPUTE           3826
PAID              3818
REFUSED           3798
Name: count, dtype: int64


In [310]:
print(
    dispositions_clean["disposition_version"].value_counts()
)

disposition_version
legacy    11726
v2        11654
v1        11620
Name: count, dtype: int64


In [311]:
dispositions_clean.to_csv(
    "../data/processed/call_dispositions_clean.csv",
    index=False
)

print("Saved call_dispositions_clean.csv")

Saved call_dispositions_clean.csv


In [312]:
import os

print(
    os.path.exists(
        "../data/processed/call_dispositions_clean.csv"
    )
)

True


## 18: data_dictionary table 

In [313]:
data_dictionary = datasets["data_dictionary"].copy()

print("Rows:", len(data_dictionary))
print("Columns:", data_dictionary.columns.tolist())
print(data_dictionary.head(10))

Rows: 143
Columns: ['dataset', 'column', 'dtype']
     dataset       column           dtype
0  borrowers  borrower_id          object
1  borrowers         name          object
2  borrowers        phone          object
3  borrowers        email          object
4  borrowers         city          object
5  borrowers   created_at  datetime64[ns]
6  borrowers   updated_at  datetime64[ns]
7  borrowers        state          object
8   accounts   account_id          object
9   accounts  borrower_id          object


In [314]:
print("Duplicate rows:", data_dictionary.duplicated().sum())

print(
    "Duplicate dataset-column pairs:",
    data_dictionary.duplicated(
        subset=["dataset", "column"]
    ).sum()
)

print("\nMissing values:")
print(data_dictionary.isna().sum())

Duplicate rows: 0
Duplicate dataset-column pairs: 0

Missing values:
dataset    0
column     0
dtype      0
dtype: int64


In [315]:
print("\nDatasets in dictionary:")
print(data_dictionary["dataset"].value_counts())


Datasets in dictionary:
dataset
accounts                  11
calls                     11
field_visits              10
payments                   9
call_attempts              9
promises_to_pay            9
complaints                 9
borrowers                  8
agents                     8
whatsapp_events            8
sms_events                 8
account_status_history     8
call_dispositions          8
daily_targeting            7
campaigns                  7
agent_sessions             7
vendor_telephony           6
Name: count, dtype: int64


In [316]:
import os

processed_path = "../data/processed"

print(os.listdir(processed_path))

['field_visits_clean.csv', 'calls_clean.csv', 'call_dispositions_clean.csv', 'agents_clean.csv', 'agent_sessions_clean.csv', 'promises_to_pay_clean.csv', 'complaints_clean.csv', 'vendor_telephony_clean.csv', 'account_status_history_clean.csv', 'campaigns_clean.csv', 'accounts_clean.csv', 'borrowers_clean.csv', 'sms_events_clean.csv', 'whatsapp_events_clean.csv', 'call_attempts_clean.csv', 'daily_targeting_clean.csv', 'payments_clean.csv']
